/** Word-specific usage notes. Key is lowercase headword. */
export const WORD_TIPS: Record<string, string> = {
  abandon: "計画・場所などを途中で投げ出す。give up より見捨てる語感",
  ability: "able の名詞。ability to do で「〜する能力」",
  abolish: "法律・制度を公式になくす。cancel より永久に廃する",
  abroad: "前置詞は付けない。go/study/live abroad",
  absence: "形容詞は absent。in one's absence で不在中",
  absolute: "absolute ＋名詞。例外を認めず言い切る。副詞は absolutely",
  absorb: "水分・情報・費用などを中に取り込む",
  abstract: "目に見えない概念。対語は concrete",
  abundant: "数が多く足りている。abundant in も使う",
  abuse: "abuse of 〜で「〜の乱用」。動詞にもなる",
  academic: "学校・研究の場面。academic year も頻出",
  accelerate: "成長・変化のスピードを上げる",
  accept: "申し出・事実を受け入れる。except（除く）と混同しない",
  access: "gain/have access to で「〜を利用できる」",
  accident: "by accident で「偶然に」。偶然の事故",
  accommodate: "人を泊める／要望に応える、の両義に注意",
  accompany: "人に付き添う。be accompanied by も覚える",
  accomplish: "課題を最後までやり遂げる。achievement の動詞側",
  accord: "reach an accord で合意に達する。according to と別語",
  account: "give an account of で説明。account for は「説明する」",
  accumulate: "少しずつ積み上げる。wealth/data と結びやすい",
  accurate: "数字・情報が狂っていない。accurate ＋名詞",
  accuse: "accuse A of B で「AをBで責める」",
  achieve: "目標を達成する。achieve a goal が定番",
  acknowledge: "誤りや功績の存在を認める。感謝の意にも",
  acquire: "技能・言語・習慣を身につける",
  adapt: "adapt to 〜で環境に合わせる。adopt（採用）と区別",
  adequate: "足りてはいるが十分すぎない。sufficient より控え目",
  adjust: "設定や位置を少しずらして合わせる",
  administer: "制度・試験・薬を運営／投与するフォーマル語",
  admire: "人の性質や行為を見てほめる",
  admit: "不利な事実を認める。入場を許す意もある",
  adopt: "方針・案を採用する。adapt（適応）と区別",
  advance: "理論・計画を前に進める。in advance は副詞句",
  advantage: "take advantage of で「〜を利用する」",
  advertise: "製品・求人を広く知らせる",
  advice: "不可算。an advice は不可。a piece of advice",
  advise: "advise ＋人＋to do。名詞は advice",
  advocate: "改革などを公に支持して唱える",
  affect: "動詞「影響する」。名詞 effect と必ず対で覚える",
  afford: "can afford to で「する余裕がある」",
  agency: "政府・旅行などの機関。agent は人",
  agenda: "会議で扱う項目表。set the agenda が定番",
  agent: "代わりに動く人。travel/real estate agent",
  aggressive: "攻めの姿勢。ビジネスでは「積極的」で訳すことが多い",
  aid: "financial aid は学資援助。動詞にもなる",
  aim: "aim to do / aim at。名詞は「目的」",
  alarm: "raise the alarm で危険を知らせる",
  alert: "stay alert で油断しない。名詞「警報」もある",
  allege: "まだ証明されていないことを主張する",
  allocate: "資源・予算・時間を割り当てる",
  allow: "allow A to do。permit より口語的",
  alter: "一部を変える。altar（祭壇）と綴り注意",
  alternative: "代わりの案。alternative to 〜",
  amaze: "人を驚かせる。amazing は物事、amazed は人",
  ambition: "将来への強い向上心。ambitious が形容詞",
  amend: "規則・文書の一部を正式に直す",
  amount: "a large amount of ＋不可算。数なら number",
  ample: "十分な余裕がある。時間・証拠と結びやすい",
  analysis: "analyze の名詞。data analysis が定番",
  ancient: "何百年も前の。old より時代が古い",
  announce: "決定・ニュースを公に知らせる",
  annual: "1年ごとの。annual report は年次報告書",
  anonymous: "名前を出さない。anonymous ＋人・情報源",
  anxious: "anxious about で心配。eager の「待ち遠しい」と区別",
  apparent: "一見してわかる。actually と対比されやすい",
  appeal: "appeal to 人で心に訴える。名詞「上訴」もある",
  appear: "姿を現す／〜らしく見える。appear to do",
  apply: "apply for 申込み。apply to 当てはまる",
  appoint: "役職に任命する。appointment は予約／任命",
  appreciate: "感謝する。I would appreciate it if が手紙定番",
  approach: "approach ＋問題で取り組む。名詞「取り組み方」",
  appropriate: "appropriate for で「〜にふさわしい」",
  approve: "approve ＋案。approve of は「賛成する」",
  approximate: "概数。approximately で「およそ」",
  argue: "論点を論理で押し出す。argue that 節",
  arise: "問題などが自然に起こる。problems arise の語順で、rise より事態の発生",
  arrange: "会合・旅行などを段取りする",
  arrest: "arrest ＋容疑者。under arrest で逮捕中",
  article: "新聞・雑誌の1本。冠詞の article とは別",
  artificial: "人工の。artificial intelligence は定番句",
  ashamed: "be/feel ashamed of。人の気持ち側",
  aspect: "物事の一面。key aspect で重要面",
  assemble: "部品を組み立てる／人が集まる",
  assert: "権利や意見をはっきり言い切る",
  assess: "価値・影響を見積もって評価する",
  assign: "assign A to B で仕事を割り振る",
  assist: "assist 人 in/with。名詞は assistance",
  associate: "associate A with B。名詞「同僚」もある",
  assume: "証拠なしにそうだと思う。assume that",
  assure: "assure 人 that。ensure は「確実にする」",
  attach: "attach A to B。添付ファイルは attachment",
  attack: "攻撃する。under attack で攻撃を受けて",
  attempt: "attempt to do。名詞「試み」と動詞が同形",
  attend: "attend a meeting。attend to は「対処する」",
  attention: "pay attention to で注意を向ける",
  attitude: "attitude toward で「〜に対する態度」",
  attract: "人や関心を引きつける。attraction は名所",
  attribute: "attribute A to B で「AをBのせい／おかげにする」",
  authentic: "偽物でない。文書・料理の「本物」",
  authority: "権限または当局。authorities で当局",
  available: "available to 人 / for 用途。在庫・日程の「空いている」",
  avoid: "avoid ＋doing。to 不定詞は取らない",
  aware: "be aware of で気づいている",
  benefit: "benefit from。名詞は「利益」。対は drawback",
  blame: "blame A for B。accuse より日常的",
  borrow: "借りる。lend は貸す。方向を取り違えない",
  brief: "短い。in brief で「要するに」。名詞「指示書」",
  cancel: "予約・便を取り消す。postpone は延期",
  cause: "cause ＋結果。理由の because と混同しない",
  chance: "by chance で偶然。chance to do で機会",
  claim: "自分の権利や事実だと言い張る。claim that",
  complement: "不足を補って完全にする。compliment（ほめる）と区別",
  compliment: "ほめ言葉を述べる。complement と綴り注意",
  comply: "comply with 規則。従うフォーマル語",
  comprise: "全体が部分を含む。consist of に近い",
  concede: "負けや相手の正しさをしぶしぶ認める",
  condemn: "道徳的に強く非難する。blame より重い",
  confirm: "予約・事実を確かめて確定する",
  consist: "consist of 部分。comprise とセットで",
  constantly: "絶え間なく。often より頻度が高い",
  constitute: "部分が全体をなす。The jury constitutes …",
  consult: "consult ＋専門家。相談して意見を聞く",
  contact: "contact ＋人。contact with は名詞用法",
  contain: "中に含む。include は「一部として入れる」",
  contend: "論争的に主張する。compete の意もある",
  contribute: "contribute to で貢献／一因となる",
  convenient: "convenient for 人。convenient to do も",
  convince: "convince 人 of / that。相手の考えを変える",
  cope: "cope with 困難。対処する自動詞",
  correspond: "correspond to/with。一致する／文通する",
  despite: "despite ＋名詞。although ＋節と使い分け",
  differ: "differ from。形容詞は different",
  distinguish: "distinguish A from B で見分ける",
  diverse: "種類が多い。diversity が名詞",
  doubt: "no doubt で疑いなく。reasonable doubt は法律",
  due: "due to で「〜が原因」。支払期限の due も",
  earn: "労働や努力の対価として得る。win は勝負",
  effect: "名詞「影響・効果」。動詞 affect と対",
  effective: "効果が出る。efficient は無駄が少ない",
  efficient: "時間や費用の無駄が少ない",
  emphasize: "強調する。名詞は emphasis、on を伴う",
  enable: "enable 人 to do で可能にする",
  encourage: "encourage 人 to do。勇気づけて促す",
  endure: "苦痛や期間に耐える。enduring は長続きする",
  enhance: "すでに良いものをさらに高める",
  ensure: "結果を確実にする。assure 人 that と区別",
  establish: "制度・関係・事実を打ち立てる",
  estimate: "概数を見積もる。名詞同形",
  evaluate: "基準に照らして評価する。assess に近い",
  eventually: "いろいろあった末にやっと。finally より経緯あり",
  evidence: "不可算。an evidence は不可",
  except: "except for ＋名詞。「〜を除いて」",
  expand: "規模・範囲を広げる。extend は長さや期限",
  expect: "expect 人 to do。予想して待つ",
  expense: "at the expense of で「〜を犠牲に」",
  explain: "explain A to B。explain me は不可",
  expose: "expose A to B でさらす。exposure が名詞",
  extend: "期限・腕・影響を伸ばす",
  extent: "to some extent で「ある程度」",
  fail: "fail to do で「しない／できない」",
  familiar: "familiar with 物事。familiar to 人",
  favor: "in favor of で賛成。favor 人 でひいき",
  feasible: "実行可能な。possible より実務的",
  feature: "目立つ特徴。動詞「目玉にする」",
  figure: "数字。figure out は「理解する」",
  focus: "focus on。名詞「焦点」",
  following: "the following で「次の」。after より文書的",
  former: "前者の。latter と対。元〜の意も",
  forth: "and so forth で「など」。put forth は提示",
  frequently: "しばしば。often のフォーマル",
  gain: "gain access/weight/experience で得る",
  generate: "電力・アイデア・利益を生み出す",
  genuine: "偽りのない。sincere は気持ち、genuine は本物",
  glance: "glance at でちらり。stare はじっと",
  gradually: "少しずつ。suddenly の対",
  grant: "grant 人 許可。take for granted は当たり前と思う",
  guarantee: "保証する。名詞同形",
  handle: "扱う・処理する。取っ手の名詞もある",
  hardly: "almost not。hard の副詞ではない",
  hesitate: "hesitate to do でためらう",
  highlight: "特に目立たせる。名詞「見どころ」",
  hire: "雇う。rent は物を借りる",
  identify: "identify A as/with。正体や原因を特定",
  ignore: "わざと見ない。neglect は怠る",
  illustrate: "例や図でわかりやすく示す",
  immediate: "すぐの。immediate ＋名詞",
  impact: "impact on。名詞が本義、動詞は近年増加",
  implement: "決定・計画を現場で実行する",
  imply: "はっきり言わずに示す。infer は読み取る側",
  impose: "impose A on B で課す",
  impress: "impress 人 with/by。印象づける",
  improve: "improve ＋状態。improve on は上回る",
  include: "一部として入れる。including は前置詞的",
  indicate: "兆候や数字が示す。indicate that",
  infer: "手がかりから推論する。imply の受け手側",
  influence: "influence on。動詞同形「影響を与える」",
  inform: "inform 人 of/that。知らせる",
  initial: "最初の。initials は頭文字",
  inquire: "inquire about。フォーマルな問い合わせ",
  insist: "insist on doing / that。強く言い張る",
  instead: "instead of ＋名詞/doing。代わりに",
  intend: "intend to do。intention が名詞",
  interest: "interest in。interest 人 は関心を持たせる",
  interpret: "意味を読み解く／通訳する",
  involve: "be involved in。含む・巻き込む",
  issue: "問題・号。issue a statement で発表する",
  justify: "justify 行為。正当だと説明する",
  lack: "lack ＋名詞（冠詞なしが多い）。lack of は名詞",
  latter: "後者の。former と対",
  launch: "製品・事業を世に出す。ロケットの打ち上げも",
  lead: "lead to 結果。lead 人 to do",
  lean: "lean on/against。lean は「lean meat」の薄い意も",
  lend: "貸す。borrow は借りる",
  likely: "be likely to do。ありそう",
  limit: "limit A to B。名詞 limits で限界",
  locate: "位置を特定する。be located で位置する",
  maintain: "維持する／主張する、の両義",
  major: "主要な。majority は過半数",
  manage: "manage to do で何とかする。管理する意も",
  manner: "in a … manner。作法は manners",
  measure: "測定する。take measures は対策を取る",
  mention: "not to mention で「〜は言うまでもなく」",
  merely: "たったの。only のフォーマル",
  method: "やり方。method of/for doing",
  minor: " minor は major の対。未成年の意も",
  monitor: "継続的に監視する。名詞「画面」",
  mutual: "互いの。mutual understanding",
  native: "native to 土地。native speaker",
  neither: "neither A nor B。どちらも〜ない",
  nevertheless: "逆接の副詞。however に近い",
  numerous: "数が多い。many のフォーマル",
  object: "object to で反対。名詞「物体／目的」",
  obtain: "努力して入手する。get のフォーマル",
  obvious: "誰の目にも明らか。obviously",
  occupy: "場所・時間・地位を占める",
  occur: "出来事が起こる自動詞。occur to 人で思いつく",
  offer: "offer 人 物。offer to do",
  omit: "わざと／誤って抜かす",
  operate: "機械や事業を動かす。operate on は手術",
  opportunity: "opportunity to do / for。chance より改まった機会",
  oppose: "oppose ＋名詞。be opposed to",
  option: "選択肢。have no option but to",
  ordinary: "普通の。extraordinary が対",
  organize: "人や行事をまとめて整える",
  origin: "origin of。形容詞 original",
  outcome: "最終的な結果。result に近いが結末寄り",
  outline: "輪郭・要点を示す。名詞「概要」",
  output: "生産量・出力。input の対",
  overcome: "困難に打ち勝つ。overcame / overcome",
  overlook: "見落とす／見逃す。見下ろす意もある",
  participate: "participate in。参加する自動詞",
  particular: "in particular で特に。特定の",
  perceive: "感覚や直感で捉える。perception が名詞",
  perform: "職務・演奏を遂行する。performance",
  permit: "permit 人 to do。名詞「許可証」",
  persist: "persist in。しつこく続ける",
  persuade: "persuade 人 to do。説き伏せる",
  phase: "段階。phase out は段階的に廃止",
  phenomenon: "複数は phenomena。観察される現象",
  policy: "組織の方針。politics（政治）と別",
  possess: "所有するフォーマル語。possession",
  postpone: "延期する。cancel は取り消し",
  potential: "potential to do。潜在的な／可能性",
  prefer: "prefer A to B。prefer to do",
  previous: "一つ前の。previous to は前置詞的",
  primary: "第一の。elementary の「初級」と区別",
  principal: "主要な／校長。principle（原則）と綴り注意",
  principle: "原則。in principle で原則として",
  proceed: "proceed to/with。先へ進む。process は過程",
  process: "過程・手順。in the process of",
  produce: "produce 製品。名詞「農産物」はアクセント注意",
  profit: "profit from。profit は利益、prophet は預言者",
  prohibit: "prohibit 人 from doing。法律で禁じる",
  promote: "促進する／昇進させる",
  prompt: "prompt 人 to do。即座の、の形容詞も",
  proper: "proper ＋名詞で適切な。properly",
  propose: "propose 案 / that。proposal が名詞",
  prove: "prove that / to be。証明する",
  provide: "provide A with B / provide B for A",
  purchase: "buy のフォーマル。名詞「購入」",
  pursue: "目標・犯人を追い続ける",
  qualify: "qualify for / as。資格を得る。qualify 人 は制限する",
  quote: "quote 人/文。quotation が引用",
  raise: "他動詞。手・資金・子どもを上げる／育てる。rise は自動詞",
  range: "range from A to B。範囲",
  rank: "順位づける。the rank of で地位",
  rate: "at a rate of。rate ＋評価する",
  rather: "rather than。would rather do",
  reach: "reach ＋場所（前置詞なし）。reach an agreement",
  realize: "気づく／実現する、の両義",
  reason: "the reason why/for。reason with は説得",
  recall: "思い出す。recall doing。リコール（回収）も",
  receive: "受け取る。accept は意志的に受け入れる",
  recognize: "見てわかる／公式に認める",
  recommend: "recommend doing / that。人に勧める",
  reduce: "reduce A to B で減らす／陥れる",
  refer: "refer to で言及／参照。reference",
  reflect: "reflect on で熟考。反射する意も",
  regard: "regard A as B。in regard to で〜に関して",
  regardless: "regardless of で「〜に関係なく」",
  reject: "申し出・案を退ける。refuse に近い",
  relate: "relate to。related to で関連する",
  release: "釈放／発売／公開する。名詞同形",
  relevant: "relevant to。今の議題に関係する",
  rely: "rely on。reliable が形容詞",
  remain: "remain ＋補語。残り続ける自動詞",
  remark: "発言する。remarkable は注目すべき",
  remind: "remind 人 of / to do。思い出させる",
  remote: "remote from。遠隔の。remote work",
  remove: "remove A from B。取り去る",
  require: "require 人 to do。requirement が要件",
  resemble: "resemble ＋名詞（前置詞なし）。似ている",
  reserve: "reserve a seat。reserve は蓄え／遠慮の名詞も",
  reside: "reside in。居住するフォーマル語",
  resign: "resign from。辞職する。re-sign と区別",
  resist: "resist ＋名詞/doing。抵抗する",
  resolve: "resolve to do / a problem。決意／解決",
  respect: "respect for。with respect to で関して",
  respond: "respond to。response が名詞",
  restore: "元の状態に戻す。restore 建物/平和",
  restrict: "restrict A to B。制限する",
  result: "result in 結果。result from 原因",
  retain: "持ち続ける。keep のフォーマル",
  reveal: "隠していたことを明らかにする",
  reverse: "逆にする。in reverse で逆に",
  review: "再検討する。review はレビュー記事の名詞も",
  revise: "改訂する。review は見直す、revisit は再訪",
  reward: "reward 人 for。報酬を与える",
  rise: "自動詞。raise は他動詞。値段・太陽が上がる",
  risk: "at risk。risk doing。危険を冒す",
  rival: "競争相手。rival ＋動詞で匹敵する",
  raw: "raw data/material。未加工の",
  scarce: "不足して珍しい。scarce な資源",
  schedule: "on schedule。動詞「予定する」",
  scheme: "計画・枠組み。米語では陰謀の語感もある",
  scope: "範囲。beyond the scope of",
  seek: "seek ＋名詞。seek to do。探し求める",
  select: "select ＋名詞。selection が名詞",
  sensitive: "sensitive to。傷つきやすい／機微な",
  sequence: "順序。a sequence of",
  series: "単複同形。a series of",
  severe: "程度が厳しい。天気・罰・症状",
  shift: "移す／転換。勤務シフトの名詞も",
  significant: "意味があるほど大きい。significant ＋差・変化",
  similar: "similar to。同じなら same",
  source: "source of。情報源・源泉",
  specific: "specific to。具体的で特定の",
  specify: "具体的に指定する。specify that",
  stable: "安定した。stabilize が動詞",
  staff: "集合的。a staff は一人を指しにくい（米では可）",
  state: "state that で述べる。state は州／国家",
  status: "地位・状態。status quo は現状",
  steady: "steady growth。着実な",
  stock: "在庫・株。stock of",
  stress: "stress ＋語で強調。under stress でストレス下",
  strict: "規則に厳しい。strict with 人",
  strike: "strike 人 as。印象を与える／ストライキ",
  structure: "構造。動詞「組織する」",
  submit: "submit A to B。提出する／服する",
  subsequent: "その後の。subsequent to",
  substance: "物質／実質。substantial は相当な",
  succeed: "succeed in doing。succeed 人 は後継する",
  sufficient: "十分な。sufficient for",
  suggest: "suggest doing / that。提案する。that 節は原形も",
  supply: "supply A with B。供給する",
  support: "支持／支える。in support of",
  suppose: "be supposed to do で「〜することになっている」",
  survive: "survive ＋事態（through 不要なことが多い）",
  suspect: "suspect 人 of。名詞「容疑者」",
  sustain: "持続させる。sustainable が形容詞",
  symbol: "symbol of。symbolic が形容詞",
  tackle: "tackle 問題。本格的に取り組む",
  target: "target ＋対象。目標値の名詞",
  temporary: "一時的な。permanent の対",
  tend: "tend to do で〜しがち",
  tension: "tension between。緊張・張力",
  term: "in terms of。term は用語／学期／条項",
  therefore: "だから。文頭やコンマのあと",
  thorough: "抜けなく徹底した。thoroughly",
  though: "though ＋節。although と同義でやや口語",
  threat: "threat to。動詞は threaten",
  thus: "こうして／したがって。文語的",
  tolerate: "tolerate ＋名詞。我慢して許す",
  transfer: "transfer A to B。移動・振替",
  transform: "transform A into B。性質まで変える",
  transit: "in transit。通過・輸送中",
  transmit: "信号・病気を送る／うつす",
  transport: "輸送する。transportation が名詞（米）",
  treat: "treat 人 as/to。扱う／おごる／治療する",
  trend: "trend toward。傾向",
  typical: "typical of。典型的な",
  ultimate: "最終・究極の。ultimate goal",
  undergo: "undergo 手術/変化。受ける（苦痛・過程）",
  underlie: "underlie 理論。根底にある。underlying",
  undertake: "事業や責任を引き受ける",
  unique: "unique to。唯一の。very unique は避けるのが無難",
  unite: "unite 人。united は結束した",
  unless: "unless ＋節＝ if not。時制に注意",
  unlike: "unlike ＋名詞。動詞 like の否定ではない",
  update: "最新にする。名詞「最新情報」",
  urban: "都市の。rural の対",
  urge: "urge 人 to do。強く促す",
  urgent: "urgent ＋要請。急ぎの",
  utilize: "use のフォーマル。実用に供する",
  vacant: "vacant 席/職。空いている",
  valid: "valid for。効力がある。invalid が対",
  valuable: "valuable な情報・経験。valued は大切にされている",
  vary: "vary from/with。形容詞 various、名詞 variety",
  vast: "vast 面積・量。非常に広い",
  vehicle: "乗り物。比喩で「媒体」",
  version: "版・言い方。a version of",
  via: "via ＋場所/手段。〜経由で",
  view: "in view of。view A as B。見解／眺め",
  violence: "不可算。violent が形容詞",
  virtual: "実質上の／仮想の。virtually でほぼ",
  visible: "visible to。見える。invisible が対",
  vision: "vision of。将来像／視力",
  vital: "vital to/for。不可欠な",
  volume: "volume of。量／巻／音量",
  voluntary: "voluntary 参加。志願の。volunteer は人／動詞",
  wage: "wage 戦争/闘争。賃金は wages が多い",
  warn: "warn 人 of/against/that。警告する",
  wealth: "wealth of で豊富な。wealthy が形容詞",
  whereas: "一方で。節をつなぐ対比",
  widespread: "widespread 支持/被害。広く行き渡った",
  willing: "be willing to do。喜んでする気がある",
  withdraw: "withdraw from。引き揚げる／引き出す",
  witness: "witness 事件。目撃する。名詞「証人」",
  wonder: "wonder if/why。不思議に思う",
  worth: "worth doing。値する。worthy of と区別",
  yield: "yield to で譲る。産出する意も",
  adventure: "seek adventure。日常を離れた危険な試み",
  apology: "offer/make an apology。動詞は apologize",
  attain: "attain success/goal。努力の末に到達する",
  balance: "keep/lose one's balance。収支の均衡にも",
  betray: "betray trust。信頼を裏返す",
  branch: "a local branch。支店／部門。本社は headquarters",
  cast: "cast a vote で投票する。原義は投げる",
  cheat: "cheat on a test。試験や配偶者への不正",
  colony: "former colony。植民地。colonial が形容詞",
  competent: "competent ＋人。実務ができる。incompetent が対",
  confer: "confer with 専門家。協議する。conference の動詞側",
  constant: "constant ＋圧・変化。途切れない",
  cooperate: "cooperate with。fully など副詞と結びやすい",
  creature: "living creature。生き物全般",
  damage: "cause/do damage。不可算が多い。動詞にもなる",
  delay: "delay a decision。延期する。delay は名詞にも",
  deserve: "deserve praise/to do。〜に値する",
  diplomat: "career diplomat。外交官。diplomatic が形容詞",
  dissolve: "dissolve in water。溶ける／解散する",
  dread: "dread failure/doing。強く恐れる",
  elite: "the elite。精鋭層。形容詞にもなる",
  entertain: "entertain guests。客をもてなす／楽しませる",
  evident: "evident ＋事実。誰の目にも明らか",
  expedition: "scientific expedition。調査のための遠征",
  faculty: "faculty member。大学の学部／教員団",
  feedback: "constructive feedback。改善意見。不可算",
  flexible: "flexible schedule。融通が利く。flexibility が名詞",
  fraction: "a small fraction of。ごく一部",
  gap: "income/generation gap。隔たり",
  graph: "bar/line graph。図表",
  hazard: "health hazard。危害の原因。hazardous",
  hostile: "hostile takeover。敵意のある。hostility が名詞",
  impulse: "on impulse。思いつきで。impulse to do",
  inhabit: "inhabit an island。土地に住む。inhabitant",
  integrity: "personal integrity。誠実さ・一貫性",
  irritate: "irritate the skin/人。いらだたせる",
  law: "pass a law。法律。the law で法全般",
  list: "waiting list。一覧。list ＋動詞で列挙",
  manipulate: "manipulate data。都合よく操る、の語感",
  medium: "through a medium。媒体。複数は media",
  miss: "miss a chance。逃す／恋しく思う",
  motive: "hidden motive。行為の裏の動機",
};

/** Extra nuance for a Japanese gloss, used when the word has no full tip. */
export const MEANING_TIPS: Record<string, string> = {
  放棄する: "途中で投げ出す",
  廃止する: "制度や法律を公式になくす",
  能力: "できる力。to do を伴いやすい",
  不在: "その場にいないこと",
  絶対的な: "例外を認めず言い切る",
  吸収する: "中に取り込む",
  抽象的な: "目に見えない概念の",
  豊富な: "数が多く足りている",
  乱用: "誤った使い方",
  学術の: "学校・研究の",
  加速する: "速さを上げる",
  受け入れる: "拒まずに取る",
  利用する権利: "access to で覚える",
  事故: "予期せず起きる災い",
  収容する: "人や要望を受け入れる",
  同行する: "一緒に行く",
  成し遂げる: "最後までやり遂げる",
  協定: "公式の合意",
  説明: "わけを述べること",
  蓄積する: "少しずつ積み上げる",
  正確な: "狂いや誤りがない",
  非難する: "責任を相手に向ける",
  達成する: "目標までたどり着く",
  認める: "事実として受け取る",
  習得する: "努力して自分のものにする",
  適応する: "環境に合わせる",
  十分な: "足りている",
  調整する: "ずれを合わせて整える",
  運営する: "組織や制度を回す",
  賞賛する: "ほめて価値を認める",
  採用する: "案や方針を取る",
  前進する: "前へ進める",
  利点: "有利な点",
  冒険: "危険を含む新しい試み",
  宣伝する: "広く知らせて勧める",
  助言: "不可算が多い",
  助言する: "どうすべきか示す",
  提唱する: "公に支持して唱える",
  影響する: "結果を変える働きをする",
  余裕がある: "can と組んで使う",
  機関: "業務を行う組織",
  議題: "会議で扱う項目",
  代理人: "代わりに動く人",
  積極的な: "攻める姿勢の",
  農業: "作物を育てる産業",
  援助: "困っている側を支えること",
  目的: "目指す先",
  警報: "危険を知らせる合図",
  油断のない: "注意を切らさない",
  異質な: "場にそぐわない",
  申し立てる: "未証明のまま主張する",
  同盟: "協力のための結びつき",
  割り当てる: "分けて渡す",
  変更する: "一部を別のものにする",
  代替案: "代わりに使える案",
  素人: "専門でない人",
  驚かせる: "相手をびっくりさせる",
  野心: "高い地位や成功を目指す心",
  修正する: "誤りを正式に直す",
  量: "不可算の大きさ",
  分析: "分けてしくみを見ること",
  祖先: "昔の血縁",
  古代の: "何百年も前の",
  怒り: "腹が立つ気持ち",
  発表する: "公に知らせる",
  年次の: "1年ごとの",
  匿名の: "名前を出さない",
  心配して: "不安で落ち着かない",
  明らかな: "見てすぐわかる",
  訴える: "心や裁判所に働きかける",
  現れる: "姿や様子が見えるようになる",
  申し込む: "許可や参加を求める",
  任命する: "役に就ける",
  感謝する: "ありがたさを伝える",
  近づく: "距離を詰める／取り組む",
  適切な: "その場にふさわしい",
  承認する: "公式によしとする",
  おおよその: "概数の",
  任意の: "決まりなく選んだ",
  建築: "建物を造ること／その様式",
  主張する: "自分の考えを押し出す",
  生じる: "自然に起こる",
  手配する: "段取りを整える",
  逮捕する: "身柄を拘束する",
  傲慢な: "人を見下す",
  記事: "媒体に載る1本の文",
  人工の: "人の手で作った",
  恥ずかしい: "面目ない気持ちの",
  側面: "物事の一面",
  攻撃: "攻めの行為",
  組み立てる: "部品を一つにする",
  保証する: "間違いなくそうすると約束する",
  妨げる: "進行を止める",
  主要な: "いちばん大切な",
  仲間: "一緒にいる人",
  従う: "規則や命令の通りにする",
  構成する: "部分が全体をつくる",
  結果: "物事の終わりに残るもの",
  一致する: "食い違わない",
  減少する: "数が減る",
  装置: "目的のための仕組みや機械",
  "〜にもかかわらず": "逆の事実があっても",
  "〜を除いて": "それを外して",
  "どちらも〜ない": "A も B も否定",
  "ほとんど〜ない": "ほぼ否定",
  位置を特定する: "どこにあるか突き止める",
  生まれながらの: "生まれつきの",
  それにもかかわらず: "逆接で話を続ける",
  決まりきった仕事: "毎回同じ手順の仕事",
  相反する感情の: "好意と反感が同時にある",
  ボイコットする: "拒否して圧力をかける",
  海外で: "国の外で。前置詞は通常不要",
};

/** Per-id notes for business / travel cards and a few TOEIC exceptions. */
export const ID_TIPS: Record<number, string> = {
  20001: "meeting agenda は会議の進行表。set/check the agenda で覚える。",
  20002: "the deadline is … で締切日。meet/miss a deadline が定番。",
  20003: "予定表そのもの。on schedule / ahead of schedule もセット。",
  20004: "人と会う約束。have/make an appointment。reservation は席や部屋。",
  20005: "大規模な会議。start/attend a conference。",
  20006: "give a presentation で発表する。資料は slides。",
  20007: "会議の公式記録。take/share the minutes。複数形のまま。",
  20008: "会議や通話の出席者。participant より会議寄り。",
  20009: "会議を進行する人。chair the meeting とも言う。",
  20010: "会合を後の日時にずらす。cancel は中止。",
  20011: "予定を別の枠に入れ直す。re- ＋ schedule。",
  20012: "日時や内容を確かめて確定する。confirm the time。",
  20013: "attend a meeting。to は付けない。出席できないは cannot attend。",
  20014: "議題を口頭で検討する。discuss ＋名詞（about は冗長）。",
  20015: "案を正式に出す。propose a new idea。",
  20016: "上長が申請をよしとする。approve the request。",
  20017: "提案を退ける。reject the proposal。",
  20018: "assign A to B で仕事を人に振る。",
  20019: "締切が最優先の。deadline-driven project。",
  20020: "urgent request は即対応が要る依頼。",
  20021: "日程が空いている。available after / on 曜日。",
  20022: "短い。brief update は要点だけの報告。",
  20023: "毎週の。weekly meeting / report。",
  20024: "毎月の。monthly report は月次報告。",
  20025: "後追いの確認連絡。send a follow-up。",
  20026: "案件の最初の会合。kickoff meeting。",
  20027: "終わりのまとめ。do a wrap-up。",
  20028: "会議後の担当作業。assign an action item。",
  20029: "遅れず。arrive/finish on time。",
  20030: "事前に。tell/book in advance。",
  20031: "ASAP と略す。返信や提出を急ぐとき。",
  20032: "今日の業務時間内に。EOD と略すこともある。",
  20033: "OOO。不在返信の定番表現。",
  20034: "短く進捗を合わせる口語。フォーマル文書では避ける。",
  20035: "次の段階へ進める。合意後によく使う。",
  20036: "会議中にメモを残す。minutes 作成の下準備。",
  20037: "発言権をもらって質問する。会議の定番。",
  20038: "認識が揃っているか確認する口語。",
  20039: "一旦置いて後で再連絡する口語。",
  20040: "予定より長引く。The meeting ran late。",
  20041: "取引相手の顧客。customer より案件単位。",
  20042: "商品・サービスを買う側。satisfied customer。",
  20043: "同じ職場の人。ask a colleague。",
  20044: "直属の上司。report to your supervisor。",
  20045: "社内の部。which department。",
  20046: "本社。複数扱いのことが多い。at headquarters。",
  20047: "支店。the Osaka branch。",
  20048: "チームで協力すること。不可算。",
  20049: "仕事の総量。heavy workload。",
  20050: "所定外の労働。do overtime / work overtime。",
  20051: "交替勤務の枠。morning/night shift。",
  20052: "人を採用する。hire a designer。",
  20053: "職を自分から辞める。resign from。",
  20054: "職位を上げる。promote 人 to 役職。",
  20055: "技能を教える。train new staff。",
  20056: "業績を評価する。evaluate performance。",
  20057: "cooperate with 人・部署。",
  20058: "任せても大丈夫。a reliable worker。",
  20059: "busy until / with。予定が埋まっている。",
  20060: "時間ややり方を変えられる。flexible hours。",
  20061: "職場にいない勤務。work remote / remotely。",
  20062: "フルタイムの。a full-time role。",
  20063: "非常勤の。a part-time job。",
  20064: "人事部。HR と略す。休暇や採用の窓口。",
  20065: "採用する側からの通知。receive a job offer。",
  20066: "有給。take paid leave。",
  20067: "勤務のない日。my day off。",
  20068: "在宅で働く。WFH。work from home today。",
  20069: "休暇を取っている状態。be on leave。",
  20070: "担当範囲。in charge of sales。",
  20071: "報告先の上司。I report to …。",
  20072: "不在の人の代わりをする。fill in for 人。",
  20073: "出勤打刻。clock in at 時刻。",
  20074: "退勤打刻。clock out at 時刻。",
  20075: "人事評価の面談や書類。the performance review is next week。",
  20076: "今後の昇進・職種の道筋。think about your career path。",
  20077: "持っている技能の一式。this role needs a new skill set。",
  20078: "チームの取りまとめ役。ask the team lead first。",
  20079: "部署全体の会議。the staff meeting is at two。",
  20080: "開局している勤務時間。office hours end at six。",
  20081: "send/reply to an email。件名は subject。",
  20082: "メールに付けるファイル。see the attachment。",
  20083: "件名欄。a clear subject line。",
  20084: "宛先。誤送信前に確認する語。",
  20085: "写しで送る。add 人 in cc。",
  20086: "受信トレイ。inbox is full。",
  20087: "未送信の下書き。save as a draft。",
  20088: "催促や再通知。send a reminder。",
  20089: "改善のための意見。give/receive feedback。不可算。",
  20090: "依頼ごと。have a request / request that。",
  20091: "返信する。reply to the email。by 期限。",
  20092: "他人にメールを回す。forward A to B。",
  20093: "ファイルを付ける。attach the file。",
  20094: "曖昧な点をはっきりさせる。clarify the point。",
  20095: "長くなった内容を短くまとめる。",
  20096: "丁寧な語調。a polite tone。",
  20097: "堅い文体。社外文書向き。",
  20098: "くだけた文体。社内メモ向き。",
  20099: "わかりやすい。a clear message。",
  20100: "件名や書き出しで「〜の件」。regarding ＋名詞。",
  20101: "情報源を示す。According to the email。",
  20102: "添付を案内する定型。Please find attached …。",
  20103: "参考送付の定型。for your reference。",
  20104: "返事や判断を求める定型。",
  20105: "to のあと動名詞。look forward to hearing。",
  20106: "末尾の結び。Kind regards, 名前。",
  20107: "先に礼を言う定型。依頼メールで多用。",
  20108: "会議の合意を前提にする書き出し。",
  20109: "変更を正式に知らせる硬い定型。",
  20110: "FYI。対応不要の共有。",
  20111: "丁寧な希望。I would like to ＋動詞。",
  20112: "依頼を一段柔らかくする定型。",
  20113: "返信遅れの定型。Sorry for the delay。",
  20114: "誤送のあと取り消す定型。",
  20115: "詳細は本文の下、と誘導する。",
  20116: "前に述べた内容を受ける。",
  20117: "途中経過をくれ、と頼む口語。",
  20118: "必要なとき連絡して、の口語。",
  20119: "折り返し連絡する。get back to you。",
  20120: "使える金額の枠。over/on budget とセット。",
  20121: "支払い請求の書類。pay/issue an invoice。",
  20122: "支払済みの証明。need a receipt。",
  20123: "概算の見積。send an estimate。",
  20124: "値引き。offer/give a discount。",
  20125: "もうけ。profit went up。",
  20126: "赤字になること。a loss。",
  20127: "かかる金額。the cost is high。",
  20128: "売値。price per unit。",
  20129: "売上高。複数扱い。sales rose。",
  20130: "契約書。sign/renew a contract。",
  20131: "取引のまとまり。close a deal。",
  20132: "仕入れ先。talk to the supplier。",
  20133: "在庫。inventory is low。",
  20134: "貨物の発送。the shipment arrives。",
  20135: "代金の支払い。payment is due。",
  20136: "返金。issue a refund。",
  20137: "税。price includes tax。",
  20138: "手数料。a small fee。",
  20139: "発注する。order ＋品物。",
  20140: "代金を払う。pay by 手段。",
  20141: "料金を課す。charge a fee。",
  20142: "節約する。save money/time。",
  20143: "増やす。increase sales。",
  20144: "減らす。reduce costs。",
  20145: "予算内で手が届く。an affordable option。",
  20146: "値段が高い。too expensive。",
  20147: "利益が出る。a profitable product。",
  20148: "支払期限が来ている。payment is due。",
  20149: "3か月ごとの。quarterly report。",
  20150: "黒字。in the black。",
  20151: "赤字。in the red。",
  20152: "損益ゼロになる。break even。",
  20153: "値下げ。announce a price cut。",
  20154: "売上のノルマ。meet/miss the sales target。",
  20155: "発注書。PO。send the purchase order。",
  20156: "銀行振込。pay by bank transfer。",
  20157: "カード払い。accept a credit card。",
  20158: "資金の出入り。watch the cash flow。",
  20159: "市場占有率。market share is growing。",
  20160: "調達から納品までの流れ。",
  20161: "費用の割に効果がある。ハイフンなし表記も多い。",
  20162: "予算内で収まる。finish on budget。",
  20163: "予算を超える。go over budget。",
  20164: "経費差し引き後の利益。net profit。",
  20165: "値引き前の総売上。gross sales。",
  20166: "1個あたりの値段。unit price。",
  20167: "勝ち方の方針。a new strategy。",
  20168: "目指す成果。set a goal。",
  20169: "出てきた成果。the result was …。",
  20170: "対処が要る問題。a small issue。",
  20171: "うまくいかない恐れ。have some risk。",
  20172: "問題の解き方。find a solution。",
  20173: "決められた手順。follow the process。",
  20174: "質。quality comes first。不可算。",
  20175: "合格ライン。meet the standard。",
  20176: "社の決まり。company policy。",
  20177: "数字や事実の材料。不可算扱いが多い。",
  20178: "報告書。finish/submit a report。",
  20179: "数値。these figures。",
  20180: "長期の向き。the trend is up。",
  20181: "数値目標。hit/miss the target。",
  20182: "今より良くする。improve the process。",
  20183: "データを分解して読む。analyze the data。",
  20184: "compare A and/with B。",
  20185: "decide to do / decide on。",
  20186: "決めた改革を現場に入れる。",
  20187: "継続的に見張る。monitor the results。",
  20188: "狙い通りの効果がある。effective method。",
  20189: "無駄が少ない。efficient way。effective と区別。",
  20190: "うまくいった。a successful launch。",
  20191: "なくてはならない。necessary change。",
  20192: "実現できる。Is … possible?",
  20193: "いちばん伝えたい点。the key point。",
  20194: "これから取る一手。the next step。",
  20195: "長い目の。long-term とハイフンも。",
  20196: "当面の。a short-term fix。",
  20197: "うまくいく定石。share a best practice。",
  20198: "実例の分析。read a case study。",
  20199: "双方得。a win-win deal。",
  20200: "決定を下す。make a decision。decide の名詞用法。",
  20201: "責任を引き受ける。take responsibility。",
  20202: "目標を達成する。meet a goal。",
  20203: "予定より遅れる。fall behind schedule。catch up の対。",
  20204: "遅れを取り戻す。catch up on work。",
  20205: "原因ややり方を理解して特定する。figure out the cause。",
  20206: "案を練ってまとめる。work out a plan。運動の意と区別。",
  20207: "数字や進捗を追い続ける。keep track of ＋名詞。",
  20208: "新しい案を出す。come up with an idea。",
  20209: "資料を上から見直す。go over the report。",
  20210: "誤りを指摘する。point out the error。",
  20211: "決めた計画を実行する。carry out the plan。",
  20212: "会場や仕組みを整える。set up the room。",
  20213: "原因を調べる。look into the issue。",
  20214: "商標・銘柄。the brand is well known。",
  20215: "宣伝の一連の活動。the campaign starts。",
  20216: "広告そのもの。see an advertisement。ad と略す。",
  20217: "売り買いの場。this market is growing。",
  20218: "競合他社。watch the competitor。",
  20219: "発売・公開の時点。the launch is next month。",
  20220: "売り物。this product is new。",
  20221: "役務。the service was excellent。",
  20222: "目玉の機能や特徴。the main feature。",
  20223: "利用者にとっての利点。the benefit for users。",
  20224: "アンケート調査。run a survey。",
  20225: "顧客対応窓口。call customer service。",
  20226: "使い心地。UX。improve the user experience。",
  20227: "狙う客層。who is the target customer。",
  20228: "報道向け発表文。send a press release。",
  20229: "交流サイト。post on social media。",
  20230: "口コミ。word of mouth。冠詞なしが多い。",
  20231: "製品を売り込む。promote a product。",
  20232: "顧客と面会する。meet a client。",
  20233: "販売を成立させる。close a sale。",
  20234: "発注する。place an order。",
  20235: "苦情を言う。make a complaint。",
  20236: "苦情を処理する。handle a claim。",
  20237: "値引きを出す。offer a discount。",
  20238: "契約書に署名する。sign a contract。",
  20239: "約束を守る。keep a promise。",
  20240: "信頼を得る。gain trust。",
  20241: "取引関係を育てる。build a relationship。",
  20242: "販売後の。after-sales support。",
  20243: "繰り返し買う。loyal customers。",
  20244: "人気がある。this model is popular。",
  20245: "競争しても勝てる。a competitive price。",
  20246: "広告する。advertise on 媒体。",
  20247: "勧める。recommend this plan。",
  20248: "条件を交渉する。negotiate the price。",
  20249: "届け先へ運ぶ。deliver on 曜日。",
  20250: "発売する。release it in 月。",
  20251: "規模を海外へ広げる。expand overseas。",
  20252: "人脈。a wide network。",
  20253: "提携関係。the partnership starts。",
  20254: "合意。reach an agreement。",
  20255: "条件。check the conditions。",
  20256: "契約の条項。these terms are fair。",
  20257: "支払期限。the due date is Monday。",
  30001: "出国・搭乗で必須の旅券。show/need my passport。",
  30002: "入国許可の査証。need a visa。国によって要否が変わる。",
  30003: "乗車券・航空券。a train/plane ticket。",
  30004: "保安検査のあとに見せる搭乗券。boarding pass。",
  30005: "搭乗口。which gate。番号と時刻を確認。",
  30006: "空港の棟。terminal two。",
  30007: "保安検査場。security is this way。",
  30008: "税関。declare は申告する。nothing to declare。",
  30009: "預け荷物。baggage claim は受取所。不可算。",
  30010: "スーツケース。my suitcase is …。",
  30011: "便の遅れ。the flight has a delay / is delayed。",
  30012: "便や予約を取り消す。cancel the flight。",
  30013: "出発する。depart at 時刻。departure が名詞。",
  30014: "到着する。arrive at 時刻/場所。",
  30015: "乗り換える。transfer in 都市。",
  30016: "空港やホテルの到着手続き。check in here。",
  30017: "ホテルの出発手続き。check out at 時刻。",
  30018: "離陸する。the plane takes off。",
  30019: "着陸する。land in 分。",
  30020: "通路側の席。an aisle seat。",
  30021: "窓側。a window seat。",
  30022: "座席。is this seat free。",
  30023: "ホーム。platform ＋番号。",
  30024: "運賃。how much is the fare。",
  30025: "片道の。a one-way ticket。",
  30026: "往復の。a round-trip ticket。英は return。",
  30027: "指定席の。a reserved seat。",
  30028: "途中停車なし。a nonstop train。",
  30029: "遅れている。the train is late。",
  30030: "早い便・時間。an early flight。",
  30031: "道に迷った。I am lost。lost-and-found と区別。",
  30032: "声をかける定型。Excuse me, where is …。",
  30033: "所要時間を聞く。How long does it take。",
  30034: "値段を聞く。How much is this。",
  30035: "場所を聞く。Where is the …。",
  30036: "案内の定型。come this way。",
  30037: "指差して「あそこ」。over there。",
  30038: "右側に。on the right。",
  30039: "左側に。on the left。",
  30040: "まっすぐ行く。go straight and …。",
  30041: "右折。turn right at …。",
  30042: "左折。turn left after …。",
  30043: "次で降りる。get off at the next stop。",
  30044: "終電。the last train。",
  30045: "バス停。the bus stop is …。",
  30046: "タクシー乗り場。the taxi stand。",
  30047: "地下鉄。take the subway。",
  30048: "空港。get to the airport。",
  30049: "駅。the station is … minutes away。",
  30050: "地図。see a map。",
  30051: "ホテル。book a hotel。",
  30052: "予約。have a reservation。",
  30053: "受付。go to reception。",
  30054: "部屋の鍵。room key。",
  30055: "客室。the room is on the … floor。",
  30056: "1人部屋の。a single room。",
  30057: "2人ベッドの部屋。a double room。",
  30058: "空き部屋。have a vacancy。",
  30059: "朝食。is breakfast included。",
  30060: "無線LAN。wifi password。",
  30061: "タオル。another towel。",
  30062: "洗濯場／洗濯。where is the laundry。",
  30063: "エレベーター。英は lift も。",
  30064: "静かな部屋を頼むとき。a quiet room。",
  30065: "今夜空いている。a room available tonight。",
  30066: "泊まる。stay for two nights。",
  30067: "予約する。book the room online。",
  30068: "モーニングコール。wake me at 時刻。",
  30069: "部屋を掃除する。clean the room。",
  30070: "到着手続きを始められる時刻。",
  30071: "部屋を空ける時刻。check-out time is …。",
  30072: "部屋への食事配達。call room service。",
  30073: "フロント。ask at the front desk。",
  30074: "冷暖房。the air conditioner is broken。",
  30075: "予備ベッド。an extra bed。",
  30076: "禁煙の。a non-smoking room。",
  30077: "眺め。a nice view。",
  30078: "食事店。the restaurant is on …。",
  30079: "献立表。see the menu。",
  30080: "注文。ready to order。",
  30081: "水。some water。",
  30082: "コーヒー。one coffee, please。",
  30083: "茶。I would like tea。",
  30084: "果汁。orange juice。",
  30085: "勘定。can I have the bill。英。米は check。",
  30086: "心づけ。leave a tip。国による。",
  30087: "辛い。too spicy。",
  30088: "甘い。very sweet。",
  30089: "熱い。the soup is hot。辛い意にも注意。",
  30090: "冷たい。a cold drink。",
  30091: "おいしい。This is delicious。",
  30092: "菜食の。a vegetarian dish。",
  30093: "allergic to ＋食材。ナッツなど。",
  30094: "空腹。I am hungry。",
  30095: "喉が渇いた。I am thirsty。",
  30096: "おすすめを聞く。What do you recommend。",
  30097: "味見する。taste this。",
  30098: "皿を分け合う。share this plate。",
  30099: "店内飲食。for here。",
  30100: "持ち帰り。to go。英は takeaway。",
  30101: "店内で食べる。dine in。",
  30102: "2人席を頼む。a table for two。",
  30103: "勘定を頼む米語。the check, please。",
  30104: "氷なし。no ice, please。",
  30105: "量を控える。just a little。",
  30106: "注文は以上。That's all。",
  30107: "食事の感想。It was great。",
  30108: "満腹。I am full。",
  30109: "主菜。the main dish。",
  30110: "副菜。a side dish。",
  30111: "定食。the set meal。",
  30112: "本日のおすすめ。today's special。",
  30113: "店。this shop is open。",
  30114: "店舗。the store closes at …。",
  30115: "値段。the price is on the tag。",
  30116: "大きさ。a larger size。",
  30117: "色。in blue / in black。",
  30118: "現金。pay in cash。",
  30119: "カード払い。pay by card。",
  30120: "釣り。keep the change。",
  30121: "袋。a bag, please。",
  30122: "特売中か聞く。Is this on sale。",
  30123: "値段が安い。This is cheaper。",
  30124: "高い。too expensive。",
  30125: "無料の。wifi is free。",
  30126: "営業中。are you open。",
  30127: "閉店。the shop is closed。",
  30128: "試着する。try this on。",
  30129: "小さすぎる。too small。",
  30130: "大きすぎる。too big。",
  30131: "見ているだけ。just looking。",
  30132: "これにします。I'll take it。",
  30133: "在庫を聞く。Do you have this in …。",
  30134: "値段を聞く全文。How much is this。",
  30135: "支払い可否。Can I pay with a card。",
  30136: "領収書を頼む。a receipt, please。",
  30137: "みやげ。a small souvenir。",
  30138: "市場。the market is busy。",
  30139: "薬局。the nearest pharmacy。",
  30140: "銀行。a bank near here。",
  30141: "博物館。the museum opens at …。",
  30142: "公園。walk in the park。",
  30143: "初対面のあいさつ。Hello, my name is …。",
  30144: "朝のあいさつ。Good morning。",
  30145: "夜のあいさつ。Good night。Good evening と区別。",
  30146: "礼。Thank you very much。",
  30147: "礼への返し。You're welcome。",
  30148: "依頼を柔らかくする。Please wait here。",
  30149: "謝罪。I am sorry I am late。",
  30150: "肯定。Yes, I understand。",
  30151: "断るときの No, thank you。",
  30152: "承知。Okay, I will wait。",
  30153: "助けが要る。I need help。",
  30154: "困りごと。there is a problem。",
  30155: "緊急事態。this is an emergency。",
  30156: "警察。call the police。",
  30157: "病院。where is the hospital。",
  30158: "医者。I need a doctor。",
  30159: "痛み。a pain here。",
  30160: "咳。have a cough。",
  30161: "熱。have a fever。",
  30162: "薬。medicine for a headache。不可算。",
  30163: "遺失物係。lost-and-found。",
  30164: "理解できない。I don't understand。",
  30165: "ゆっくり話して、と頼む定型。",
  30166: "英語が通じるか聞く定型。",
  30167: "助けを求める定型。Can you help me。",
  30168: "紛失を伝える。I lost my ＋持ち物。",
  30169: "タクシーを呼んでもらう。call a taxi。",
  30170: "気分が悪い。I feel sick。",
  30171: "痛い。It hurts here。",
  30172: "少々待ちを頼む。Wait a moment。",
  30173: "別れの定型。See you tomorrow。",
  30174: "初対面。Nice to meet you。",
  30175: "自己紹介。My name is …。",
  30176: "出身。I am from …。",
  30177: "天気。the weather is nice。不可算。",
  30178: "雨。it may rain。",
  30179: "晴れ。it is sunny。",
  30180: "曇り。it is cloudy。",
  30181: "暖かい。it is warm outside。",
  30182: "肌寒い。it is chilly。",
  30183: "傘。need an umbrella。",
  30184: "今日。what are you doing today。",
  30185: "明日。see you tomorrow。",
  30186: "昨日。I arrived yesterday。",
  30187: "朝。in the morning。",
  30188: "夕方。in the evening。",
  30189: "夜の時間帯。The city is quiet at night。",
  30190: "週末。this weekend。",
  30191: "友人。meet a friend。",
  30192: "家族。with my family。集合名詞。",
  30193: "写真。take a photo。",
  30194: "電話。my phone is …。",
  30195: "充電器。need a charger。",
  30196: "現金不可。this shop is cashless。",
  30197: "地元の。local food。",
  30198: "有名な。this temple is famous。",
  30199: "混んだ。the train is crowded。",
  30200: "安全な。safe at night。",
  30201: "近い。near here。",
  30202: "距離が遠い。The hotel is not far。",
  30203: "楽しむ。enjoy your stay。",
  30204: "訪れる。visit the castle。",
  30205: "歩く。walk from here。",
  30206: "休む。need to rest。",
  30207: "待つ。wait here。",
  30208: "見る。look at …。",
  30209: "別れ際の定型。Have a nice day。",
  30210: "労い・別れ。Take care。",
  30211: "楽しんで。Have fun in 地名。",
  30212: "見物する。see the sights。",
  30213: "一休みする。take a break。",
  30214: "体を休める。get some rest。",
  30215: "電池切れ。out of battery。",
  30216: "撮影してよいか聞く。Can I take a photo。",
  30217: "時刻を聞く。What time is it。",
  30218: "また後で。See you later。",
  30219: "借家ではなく集合住宅。rent an apartment nearby。",
  30220: "毎月の部屋代。pay the rent on Friday。",
  30221: "部屋の持ち主。call the landlord about this。",
  30222: "隣に住む人。my neighbor is kind。",
  30223: "郵便物の箱。check the mailbox later。",
  30224: "捨てるごみ。take out the garbage tonight。",
  30225: "資源として出す。recycle these bottles。",
  30226: "電気ガス水道。utilities are not included。",
  30227: "停電は go out。the electricity went out。",
  30228: "調理・暖房のガス。turn off the gas first。",
  30229: "回線。the internet is too slow。",
  30230: "暗証文字列。forgot the wifi password。",
  30231: "鍵をかける。lock the door behind you。",
  30232: "玄関のベル。ring the doorbell twice。",
  30233: "上階へ。they live upstairs now。",
  30234: "下階へ。the laundry is downstairs。",
  30235: "家具が最初からある。fully furnished。",
  30236: "自分で家具を入れる。the place is unfurnished。",
  30237: "入居時に預ける金。paid the deposit。",
  30238: "借りる契約書。sign the lease this week。",
  30239: "荷物を入れて住み始める。move in on Sunday。",
  30240: "部屋を空ける。move out next month。",
  30241: "騒音を控える時間。quiet hours start at ten。",
  30242: "日常の食材。buy groceries。",
  30243: "大型食品店。the supermarket closes at nine。",
  30244: "野菜と果物。fresh produce is over there。",
  30245: "凍らせた食品。some frozen food。",
  30246: "店内の台車。get a shopping cart first。",
  30247: "会計場。the checkout line is long。",
  30248: "現金の出し入れ。an ATM nearby。",
  30249: "口座から出す。withdraw some cash。",
  30250: "預金口座。opened a bank account。",
  30251: "郵便の窓口。the post office closes soon。",
  30252: "配達された箱。got a package today。",
  30253: "手紙や通知。did I get any mail。",
  30254: "居所の書き方。your home address。",
  30255: "番地の数字。write the zip code here。",
  30256: "小さな病院。go to the clinic today。",
  30257: "医療などの保障。health insurance。",
  30258: "薬の指示書。this prescription filled。",
  30259: "通いの移動。commute by train。",
  30260: "仕事場の建物。at the office now。",
  30261: "同じ職場の人。ask your coworker first。",
  30262: "直属の上の人。my boss is away。",
  30263: "月ごとの報酬。salary is paid monthly。",
  30264: "体を動かす店。go to the gym after work。",
  30265: "会費を払う資格。a gym membership。",
  30266: "携帯の識別板。a new SIM card。",
  30267: "通信量の契約。change my data plan。",
  30268: "ごみを入れる袋。another trash bag。",
  30269: "皿を洗う機械。run the dishwasher tonight。",
  30270: "洗う粉や液。out of detergent。",
  30271: "水回りの職人。call a plumber tomorrow。",
  30272: "壊れた物を直す。repair this sink。",
  30273: "動かない状態。the heater is broken。",
  30274: "水がにじむ。there is a leak。",
  30275: "音が大きい。too noisy at night。",
  30276: "周り一帯。this neighborhood is quiet。",
  30277: "街の中心。walk downtown later。",
  30278: "車を止めること。is parking free here。",
  30279: "運転の許可証。show your driver's license。",
  30280: "本人確認の札。a photo ID card。",
  30281: "滞在を示すカード。your residence card。",
  30282: "役所の本庁。go to city hall。",
  30283: "本を借りる場所。the library is free。",
  30284: "昼夜開く小さな店。a convenience store。",
  30285: "工具や部品の店。the hardware store first。",
  30286: "二輪の足。commute by bike now。",
  30287: "止め方の罰金。got a parking ticket。",
  30288: "再利用のごみ。put this in recycling。",
  30289: "水道の請求。pay the water bill today。",
  30290: "部屋を温める装置。the heating is on。",
  30291: "焼く箱。preheat the oven first。",
  30292: "冷やす箱。the fridge is almost empty。",
  30293: "水を流す槽。the sink is clogged。",
  30294: "便所の紙。more toilet paper。",
  30295: "掃く道具。where is the broom。",
  30296: "吸い取る掃除。vacuum the floor please。",
  30297: "明かりの球。change the light bulb。",
  30298: "住み始める日。the move-in date。",
  30299: "安否の定番。how are you today。",
  30300: "安否への返し。I'm fine thank you。",
  30301: "軽い安否。what's up with you。",
  30302: "久しぶりの再会。long time no see。",
  30303: "当然だ、の返事。of course I can help。",
  30304: "気にするな、の返し。no problem at all。",
  30305: "取り消しや慰め。never mind about that。",
  30306: "同意の考え。I think so too。",
  30307: "穏やかな否定。I don't think so。",
  30308: "意見が同じ。I agree with you。",
  30309: "不確かな可能性。maybe after work。",
  30310: "高い見込み。I will probably go。",
  30311: "理由をつなぐ。stayed because it rained。",
  30312: "条件。call me if you need。",
  30313: "欲求。I want some cold water。",
  30314: "欠かせない。I need your help now。",
  30315: "好み。I like this song。",
  30316: "比べて選ぶ。prefer tea to coffee。",
  30317: "返前提で借りる。borrow this pen。",
  30318: "相手に渡して貸す。lend you one。",
  30319: "借りた物を戻す。return it tomorrow。",
  30320: "集まりへ呼ぶ。invite you tonight。",
  30321: "仲間に入る。want to join us。",
  30322: "気軽に過ごす。hang out later。",
  30323: "生まれた日。happy birthday to you。",
  30324: "祝いの集まり。come to my party。",
  30325: "楽しみの習い。what is your hobby。",
  30326: "映写作品。watch a movie tonight。",
  30327: "音の楽しみ。I like this music。",
  30328: "体力が落ちた。so tired today。",
  30329: "手が空かない。busy until five。",
  30330: "予定のない時間。free time Sunday。",
  30331: "速度を上げる。please hurry up。",
  30332: "記憶を引き出す。cannot remember his name。",
  30333: "記憶から落とす。do not forget your keys。",
  30334: "選択を固める。decide after lunch。",
  30335: "候補から取る。you can choose first。",
  30336: "わかりやすく述べる。explain that again。",
  30337: "同じことを言う。repeat that slowly。",
  30338: "文字を一つずつ。spell your name。",
  30339: "文字にする。write it down。",
  30340: "先へ届ける。send a message。",
  30341: "短い知らせ。leave a message。",
  30342: "短い文を送る。text me after work。",
  30343: "かけ直す依頼。call me back soon。",
  30344: "顔を合わせる。meet after work。",
  30345: "人を引き合わせる。introduce my friend。",
  30346: "祝いの言葉。congratulations on the job。",
  30347: "励まし。good luck tomorrow。",
  30348: "杯を合わせる。cheers to the weekend。",
  30349: "探している、の切り出し。I'm looking for。",
  30350: "席の確認。is this seat taken。",
  30351: "一時預ける依頼。could you hold this。",
  30352: "予定の会議。I have a meeting at three。",
  30353: "職場の早退。can I leave early。",
  30354: "後で届ける約束。I'll send it tonight。",
  30355: "電話番号を聞く。what's your number。",
  30356: "連絡先のメール。what's your email。",
  30357: "短い休憩の誘い。let's grab coffee。",
  30358: "聞いてから返す。I'll check with my boss。",
  30359: "今は無理、の延期。can we talk later。",
  30360: "到着が遅れ気味。I'm running late now。",
  30361: "到着の約束。I'll be there at five。",
  30362: "提案への賛成。that sounds good。",
  30363: "都合が合う。that works for me。",
  30364: "決めきれない。I'm not sure yet。",
  30365: "即答しない。let me think about it。",
  30366: "遅刻の詫び。sorry I'm late again。",
  30367: "待たせた礼。thanks for waiting。",
  30368: "先を譲る。after you please。",
  30369: "先に進めて、の許可。please go ahead。",
  30370: "急かさない。take your time。",
  30371: "理解した合図。I got it thanks。",
  30372: "誤りを認める。I made a mistake。",
  30373: "相手を安心させる。no worries at all。",
  30374: "礼への丁寧な返し。my pleasure to help。",
  30375: "カジュアルな別れ。catch you later then。",
  30376: "無理するな。take it easy tonight。",
  30377: "縁を切らさない。keep in touch。",
  30378: "否定を強める。of course not。",
  30379: "電話やドアへ行く。I'll get it。"
};
