import { writeFileSync } from "node:fs";

function pack(id0, rows) {
  const per = Math.ceil(rows.length / 3);
  return rows.map((row, i) => {
    const unit = Math.min(3, Math.floor(i / per) + 1);
    const part = unit;
    const [word, pos, meaning, phrase, phraseJa] = row;
    return { id: id0 + i, word, ipa: "", pos, meaning, phrase, phraseJa, part, unit };
  });
}

const business = pack(20001, [
  ["agenda", "名", "議題", "Check the meeting agenda.", "会議の議題を確認してください。"],
  ["deadline", "名", "締め切り", "The deadline is Friday.", "締め切りは金曜日です。"],
  ["schedule", "名", "予定", "I will send the schedule today.", "今日中に予定を送ります。"],
  ["appointment", "名", "予約", "I have an appointment at ten.", "10時に予約があります。"],
  ["conference", "名", "会議", "The conference starts at nine.", "会議は9時に始まります。"],
  ["presentation", "名", "発表", "She gave a short presentation.", "彼女は短い発表をしました。"],
  ["minutes", "名", "議事録", "Please share the minutes.", "議事録を共有してください。"],
  ["attendee", "名", "出席者", "Ten attendees joined the call.", "10人の出席者が通話に参加しました。"],
  ["chairperson", "名", "議長", "The chairperson opened the meeting.", "議長が会議を始めました。"],
  ["postpone", "動", "延期する", "We should postpone the meeting.", "会議を延期すべきです。"],
  ["reschedule", "動", "予定を変更する", "Can we reschedule the call?", "通話の予定を変更できますか。"],
  ["confirm", "動", "確認する", "Please confirm the time.", "時間を確認してください。"],
  ["attend", "動", "出席する", "I cannot attend tomorrow.", "明日は出席できません。"],
  ["discuss", "動", "話し合う", "Let’s discuss the plan.", "計画について話し合いましょう。"],
  ["propose", "動", "提案する", "He proposed a new idea.", "彼は新しい案を提案しました。"],
  ["approve", "動", "承認する", "The manager approved the request.", "上司がその依頼を承認しました。"],
  ["reject", "動", "却下する", "They rejected the proposal.", "彼らはその提案を却下しました。"],
  ["assign", "動", "割り当てる", "I assigned the task to Ken.", "その仕事をケンに割り当てました。"],
  ["deadline-driven", "形", "締め切り重視の", "This is a deadline-driven project.", "これは締め切り重視の案件です。"],
  ["urgent", "形", "急ぎの", "This is an urgent request.", "これは急ぎの依頼です。"],
  ["available", "形", "都合がつく", "I am available after lunch.", "昼過ぎなら都合がつきます。"],
  ["brief", "形", "短い", "Give a brief update.", "短い報告をしてください。"],
  ["weekly", "形", "週次の", "We have a weekly meeting.", "週次の会議があります。"],
  ["monthly", "形", "月次の", "The monthly report is ready.", "月次報告の準備ができています。"],
  ["follow-up", "名", "続きの確認", "I will send a follow-up email.", "続きの確認メールを送ります。"],
  ["kickoff", "名", "開始会合", "The kickoff is on Monday.", "開始会合は月曜日です。"],
  ["wrap-up", "名", "まとめ", "Let’s do a quick wrap-up.", "簡単にまとめましょう。"],
  ["action item", "句", "宿題・次の作業", "This is your action item.", "これがあなたの宿題です。"],
  ["on time", "句", "時間どおりに", "Please arrive on time.", "時間どおりに来てください。"],
  ["in advance", "句", "前もって", "Tell me in advance.", "前もって教えてください。"],
  ["as soon as possible", "句", "できるだけ早く", "Reply as soon as possible.", "できるだけ早く返信してください。"],
  ["by the end of the day", "句", "今日中に", "Finish it by the end of the day.", "今日中に終わらせてください。"],
  ["out of office", "句", "不在", "I am out of office today.", "本日は不在です。"],
  ["touch base", "句", "軽く連絡する", "Let’s touch base tomorrow.", "明日軽く連絡を取りましょう。"],
  ["move forward", "句", "先に進める", "We can move forward now.", "これで先に進めます。"],
  ["take notes", "句", "メモを取る", "Please take notes.", "メモを取ってください。"],
  ["raise a question", "句", "質問する", "May I raise a question?", "質問してもよろしいですか。"],
  ["on the same page", "句", "認識が一致して", "Are we on the same page?", "認識は一致していますか。"],
  ["circle back", "句", "後で戻る", "I will circle back later.", "後でまた戻ります。"],
  ["run late", "句", "遅れる", "The meeting may run late.", "会議が遅れるかもしれません。"],
  ["client", "名", "顧客", "The client asked for a change.", "顧客が変更を求めました。"],
  ["customer", "名", "お客様", "The customer was satisfied.", "お客様は満足していました。"],
  ["colleague", "名", "同僚", "Ask your colleague for help.", "同僚に助けを求めてください。"],
  ["supervisor", "名", "上司", "Talk to your supervisor first.", "まず上司に相談してください。"],
  ["department", "名", "部署", "Which department do you work in?", "どの部署で働いていますか。"],
  ["headquarters", "名", "本社", "She works at headquarters.", "彼女は本社で働いています。"],
  ["branch", "名", "支店", "He moved to the Osaka branch.", "彼は大阪支店に移りました。"],
  ["teamwork", "名", "協力", "Teamwork is important here.", "ここでは協力が大切です。"],
  ["workload", "名", "仕事量", "My workload is heavy this week.", "今週は仕事量が多いです。"],
  ["overtime", "名", "残業", "I did two hours of overtime.", "2時間残業しました。"],
  ["shift", "名", "勤務時間帯", "I work the morning shift.", "朝の勤務時間帯です。"],
  ["hire", "動", "雇う", "We need to hire a designer.", "デザイナーを雇う必要があります。"],
  ["resign", "動", "辞職する", "He resigned last month.", "彼は先月辞職しました。"],
  ["promote", "動", "昇進させる", "They promoted her to manager.", "彼女は課長に昇進しました。"],
  ["train", "動", "研修する", "We will train new staff.", "新入社員を研修します。"],
  ["evaluate", "動", "評価する", "We evaluate performance yearly.", "毎年成果を評価します。"],
  ["cooperate", "動", "協力する", "Please cooperate with the team.", "チームに協力してください。"],
  ["reliable", "形", "信頼できる", "She is a reliable worker.", "彼女は信頼できる社員です。"],
  ["busy", "形", "忙しい", "I am busy until three.", "3時まで忙しいです。"],
  ["flexible", "形", "融通が利く", "The hours are flexible.", "勤務時間は融通が利きます。"],
  ["remote", "形", "遠隔の", "I work remote on Fridays.", "金曜は遠隔で働きます。"],
  ["full-time", "形", "フルタイムの", "This is a full-time role.", "これはフルタイムの仕事です。"],
  ["part-time", "形", "パートの", "She has a part-time job.", "彼女はパートの仕事があります。"],
  ["human resources", "句", "人事", "Ask human resources about leave.", "休暇のことは人事に聞いてください。"],
  ["job offer", "句", "採用通知", "I received a job offer.", "採用通知を受け取りました。"],
  ["paid leave", "句", "有給休暇", "I will take paid leave.", "有給休暇を取ります。"],
  ["day off", "句", "休みの日", "Monday is my day off.", "月曜は休みの日です。"],
  ["work from home", "句", "在宅勤務する", "I work from home today.", "今日は在宅勤務です。"],
  ["on leave", "句", "休暇中", "She is on leave this week.", "彼女は今週休暇中です。"],
  ["in charge of", "句", "担当して", "I am in charge of sales.", "私は営業を担当しています。"],
  ["report to", "句", "上司が〜である", "I report to Ms. Aoki.", "上司は青木さんです。"],
  ["fill in", "句", "代わりをする", "Can you fill in for me?", "代わりをしてもらえますか。"],
  ["clock in", "句", "出勤する", "Please clock in at nine.", "9時に出勤してください。"],
  ["clock out", "句", "退勤する", "I clock out at six.", "6時に退勤します。"],
  ["performance review", "句", "人事評価", "The performance review is next week.", "人事評価は来週です。"],
  ["career path", "句", "キャリアの道", "Think about your career path.", "自分のキャリアの道を考えてください。"],
  ["skill set", "句", "技能の集まり", "This role needs a new skill set.", "この仕事には新しい技能が要ります。"],
  ["team lead", "句", "チームの責任者", "Ask the team lead first.", "まずチームの責任者に聞いてください。"],
  ["staff meeting", "句", "職員会議", "The staff meeting is at two.", "職員会議は2時です。"],
  ["office hours", "句", "勤務時間", "Office hours end at six.", "勤務時間は6時までです。"],
  ["email", "名", "電子メール", "I sent the email this morning.", "今朝メールを送りました。"],
  ["attachment", "名", "添付ファイル", "Please open the attachment.", "添付ファイルを開いてください。"],
  ["subject", "名", "件名", "Write a clear subject line.", "わかりやすい件名を書いてください。"],
  ["recipient", "名", "宛先", "Check the recipient again.", "宛先をもう一度確認してください。"],
  ["cc", "名", "写しの送信", "Add her in cc.", "彼女を写しに入れてください。"],
  ["inbox", "名", "受信箱", "My inbox is full.", "受信箱がいっぱいです。"],
  ["draft", "名", "下書き", "I saved it as a draft.", "下書きとして保存しました。"],
  ["reminder", "名", "催促", "Send a reminder tomorrow.", "明日催促を送ってください。"],
  ["feedback", "名", "意見・感想", "Thank you for your feedback.", "ご意見をありがとうございます。"],
  ["request", "名", "依頼", "I have a small request.", "小さな依頼があります。"],
  ["reply", "動", "返信する", "Please reply by noon.", "正午までに返信してください。"],
  ["forward", "動", "転送する", "Forward this to the team.", "これをチームに転送してください。"],
  ["attach", "動", "添付する", "Did you attach the file?", "ファイルを添付しましたか。"],
  ["clarify", "動", "はっきりさせる", "Let me clarify the point.", "その点をはっきりさせます。"],
  ["summarize", "動", "要約する", "Summarize the email in two lines.", "メールを2行で要約してください。"],
  ["polite", "形", "丁寧な", "Use a polite tone.", "丁寧な口調にしてください。"],
  ["formal", "形", "堅い", "This letter is too formal.", "この手紙は堅すぎます。"],
  ["informal", "形", "くだけた", "The note is informal.", "そのメモはくだけています。"],
  ["clear", "形", "わかりやすい", "Your message is clear.", "メッセージはわかりやすいです。"],
  ["regarding", "前", "〜に関して", "I am writing regarding the invoice.", "請求書に関して書いています。"],
  ["according to", "句", "〜によれば", "According to the email, it is done.", "メールによれば完了しています。"],
  ["please find attached", "句", "添付をご覧ください", "Please find attached the file.", "添付のファイルをご覧ください。"],
  ["for your reference", "句", "参考までに", "I send this for your reference.", "参考までに送ります。"],
  ["let me know", "句", "知らせてください", "Let me know if you agree.", "賛成なら知らせてください。"],
  ["look forward to", "句", "楽しみにする", "I look forward to your reply.", "返信を楽しみにしています。"],
  ["kind regards", "句", "敬具", "Kind regards, Aya.", "敬具 アヤ"],
  ["thank you in advance", "句", "前もってお礼を", "Thank you in advance.", "前もってお礼を申し上げます。"],
  ["as discussed", "句", "話し合ったとおり", "As discussed, we will wait.", "話し合ったとおり、待ちます。"],
  ["please be advised", "句", "お知らせします", "Please be advised of the change.", "変更をお知らせします。"],
  ["for your information", "句", "ご参考まで", "This is for your information.", "これはご参考までです。"],
  ["I would like to", "句", "〜したい", "I would like to confirm the date.", "日付を確認したいです。"],
  ["could you please", "句", "〜していただけますか", "Could you please check this?", "これを確認していただけますか。"],
  ["sorry for the delay", "句", "遅れてすみません", "Sorry for the delay in reply.", "返信が遅れてすみません。"],
  ["please ignore", "句", "無視してください", "Please ignore my last email.", "先のメールは無視してください。"],
  ["see below", "句", "以下を見て", "See below for details.", "詳細は以下を見てください。"],
  ["as mentioned", "句", "述べたように", "As mentioned, the file is ready.", "述べたように、ファイルはできています。"],
  ["keep me posted", "句", "経過を知らせて", "Keep me posted on the result.", "結果の経過を知らせてください。"],
  ["reach out", "句", "連絡する", "Please reach out if needed.", "必要なら連絡してください。"],
  ["get back to", "句", "折り返す", "I will get back to you today.", "今日折り返します。"],
  ["budget", "名", "予算", "The budget is limited.", "予算は限られています。"],
  ["invoice", "名", "請求書", "Please pay the invoice.", "請求書を支払ってください。"],
  ["receipt", "名", "領収書", "I need a receipt.", "領収書が必要です。"],
  ["estimate", "名", "見積もり", "Send an estimate tomorrow.", "明日見積もりを送ってください。"],
  ["discount", "名", "割引", "We can offer a small discount.", "少し割引できます。"],
  ["profit", "名", "利益", "Profit went up this year.", "今年は利益が増えました。"],
  ["loss", "名", "損失", "The project was a loss.", "その案件は損失でした。"],
  ["cost", "名", "費用", "The cost is too high.", "費用が高すぎます。"],
  ["price", "名", "価格", "What is the price per unit?", "1個あたりの価格はいくらですか。"],
  ["sales", "名", "売上", "Sales rose in June.", "6月は売上が伸びました。"],
  ["contract", "名", "契約", "Please sign the contract.", "契約に署名してください。"],
  ["deal", "名", "取引", "We closed the deal.", "取引がまとまりました。"],
  ["supplier", "名", "仕入先", "Talk to the supplier today.", "今日仕入先と話してください。"],
  ["inventory", "名", "在庫", "Inventory is low.", "在庫が少ないです。"],
  ["shipment", "名", "発送", "The shipment arrives Friday.", "発送は金曜に届きます。"],
  ["payment", "名", "支払い", "Payment is due next week.", "支払いは来週です。"],
  ["refund", "名", "返金", "They issued a refund.", "返金が出ました。"],
  ["tax", "名", "税", "The price includes tax.", "価格には税が含まれます。"],
  ["fee", "名", "手数料", "There is a small fee.", "少し手数料がかかります。"],
  ["order", "動", "発注する", "We ordered more paper.", "紙を追加発注しました。"],
  ["pay", "動", "支払う", "Please pay by bank transfer.", "銀行振込で支払ってください。"],
  ["charge", "動", "請求する", "They charged an extra fee.", "追加の手数料を請求されました。"],
  ["save", "動", "節約する", "This plan can save money.", "この案ならお金を節約できます。"],
  ["increase", "動", "増やす", "We need to increase sales.", "売上を増やす必要があります。"],
  ["reduce", "動", "減らす", "Reduce unnecessary costs.", "不要な費用を減らしてください。"],
  ["affordable", "形", "手ごろな", "We need an affordable option.", "手ごろな選択肢が必要です。"],
  ["expensive", "形", "高い", "That tool is expensive.", "その道具は高いです。"],
  ["profitable", "形", "もうかる", "This product is profitable.", "この商品はもうかります。"],
  ["due", "形", "期限の", "The payment is due today.", "支払いは本日期限です。"],
  ["quarterly", "形", "四半期の", "This is a quarterly report.", "これは四半期の報告です。"],
  ["in the black", "句", "黒字で", "The shop is in the black.", "その店は黒字です。"],
  ["in the red", "句", "赤字で", "The unit is in the red.", "その部門は赤字です。"],
  ["break even", "句", "損益なしになる", "We will break even next year.", "来年損益なしになります。"],
  ["price cut", "句", "値下げ", "They announced a price cut.", "値下げが発表されました。"],
  ["sales target", "句", "売上目標", "We missed the sales target.", "売上目標に届きませんでした。"],
  ["purchase order", "句", "発注書", "Send the purchase order today.", "今日発注書を送ってください。"],
  ["bank transfer", "句", "銀行振込", "Pay by bank transfer.", "銀行振込で払ってください。"],
  ["credit card", "句", "クレジットカード", "We accept a credit card.", "クレジットカードが使えます。"],
  ["cash flow", "句", "資金の流れ", "Watch the cash flow closely.", "資金の流れをよく見てください。"],
  ["market share", "句", "市場占有率", "Our market share is growing.", "市場占有率は伸びています。"],
  ["supply chain", "句", "供給の流れ", "The supply chain was delayed.", "供給の流れが遅れました。"],
  ["cost effective", "句", "費用対効果のよい", "This is a cost effective choice.", "これは費用対効果のよい選択です。"],
  ["on budget", "句", "予算内で", "We finished on budget.", "予算内で終わりました。"],
  ["over budget", "句", "予算超過で", "The work went over budget.", "作業が予算を超えました。"],
  ["net profit", "句", "純利益", "Net profit rose by five percent.", "純利益が5パーセント増えた。"],
  ["gross sales", "句", "総売上", "Gross sales were strong.", "総売上は好調でした。"],
  ["unit price", "句", "単価", "Check the unit price first.", "まず単価を確認してください。"],
  ["strategy", "名", "戦略", "We need a new strategy.", "新しい戦略が必要です。"],
  ["goal", "名", "目標", "Set a clear goal.", "はっきりした目標を立ててください。"],
  ["result", "名", "結果", "The result was better than expected.", "結果は予想より良かったです。"],
  ["issue", "名", "問題", "There is a small issue.", "小さな問題があります。"],
  ["risk", "名", "危険", "This plan has some risk.", "この案には危険があります。"],
  ["solution", "名", "解決策", "We found a simple solution.", "簡単な解決策が見つかりました。"],
  ["process", "名", "手順", "Follow the process.", "手順に従ってください。"],
  ["quality", "名", "質", "Quality comes first.", "質が一番です。"],
  ["standard", "名", "基準", "This meets the standard.", "これは基準を満たしています。"],
  ["policy", "名", "方針", "Read the company policy.", "会社の方針を読んでください。"],
  ["data", "名", "資料・数値", "The data supports the idea.", "資料がその考えを支えています。"],
  ["report", "名", "報告書", "Finish the report today.", "今日中に報告書を仕上げてください。"],
  ["figure", "名", "数値", "These figures look correct.", "これらの数値は正しそうです。"],
  ["trend", "名", "傾向", "The trend is going up.", "傾向は上向きです。"],
  ["target", "名", "目標値", "We hit the target.", "目標値に届きました。"],
  ["improve", "動", "改善する", "We must improve the process.", "手順を改善しなければなりません。"],
  ["analyze", "動", "分析する", "Analyze the latest data.", "最新の資料を分析してください。"],
  ["compare", "動", "比べる", "Compare the two plans.", "2つの案を比べてください。"],
  ["decide", "動", "決める", "We will decide tomorrow.", "明日決めます。"],
  ["implement", "動", "実行する", "They will implement the change.", "その変更を実行します。"],
  ["monitor", "動", "監視する", "Monitor the results weekly.", "結果を毎週監視してください。"],
  ["effective", "形", "効果的な", "This is an effective method.", "これは効果的な方法です。"],
  ["efficient", "形", "能率のよい", "Find a more efficient way.", "より能率のよい方法を探してください。"],
  ["successful", "形", "成功した", "The launch was successful.", "発売は成功しました。"],
  ["necessary", "形", "必要な", "Is this change necessary?", "この変更は必要ですか。"],
  ["possible", "形", "可能な", "Is an earlier date possible?", "より早い日は可能ですか。"],
  ["key point", "句", "要点", "This is the key point.", "これが要点です。"],
  ["next step", "句", "次の段階", "What is the next step?", "次の段階は何ですか。"],
  ["long term", "句", "長期の", "Think about the long term.", "長期のことを考えてください。"],
  ["short term", "句", "短期の", "This is a short term fix.", "これは短期の手当てです。"],
  ["best practice", "句", "よいやり方", "Share the best practice.", "よいやり方を共有してください。"],
  ["case study", "句", "事例研究", "Read this case study.", "この事例研究を読んでください。"],
  ["win-win", "句", "双方得な", "We want a win-win deal.", "双方得な取引にしたいです。"],
  ["make a decision", "句", "決定する", "We need to make a decision.", "決定する必要があります。"],
  ["take responsibility", "句", "責任を持つ", "I will take responsibility.", "私が責任を持ちます。"],
  ["meet a goal", "句", "目標を達成する", "We met the goal this month.", "今月は目標を達成しました。"],
  ["fall behind", "句", "遅れる", "Do not fall behind schedule.", "予定より遅れないでください。"],
  ["catch up", "句", "追いつく", "I need to catch up on work.", "仕事に追いつく必要があります。"],
  ["figure out", "句", "理解する", "Let’s figure out the cause.", "原因を理解しましょう。"],
  ["work out", "句", "解決する", "We can work out a plan.", "計画を解決できます。"],
  ["keep track of", "句", "把握する", "Keep track of the numbers.", "数字を把握してください。"],
  ["come up with", "句", "考え出す", "Come up with a better idea.", "よりよい案を考え出してください。"],
  ["go over", "句", "見直す", "Let’s go over the report.", "報告書を見直しましょう。"],
  ["point out", "句", "指摘する", "She pointed out the error.", "彼女がその誤りを指摘しました。"],
  ["carry out", "句", "実行する", "Carry out the plan as agreed.", "合意どおり計画を実行してください。"],
  ["set up", "句", "準備する", "Set up the meeting room.", "会議室を準備してください。"],
  ["look into", "句", "調べる", "I will look into the issue.", "その問題を調べます。"],
  ["brand", "名", "商標", "The brand is well known.", "その商標はよく知られています。"],
  ["campaign", "名", "宣伝活動", "The campaign starts in May.", "宣伝活動は5月に始まります。"],
  ["advertisement", "名", "広告", "I saw the advertisement online.", "ネットでその広告を見ました。"],
  ["market", "名", "市場", "This market is growing.", "この市場は伸びています。"],
  ["competitor", "名", "競合", "Watch the competitor closely.", "競合をよく見てください。"],
  ["launch", "名", "発売", "The launch is next month.", "発売は来月です。"],
  ["product", "名", "製品", "This product is new.", "この製品は新しいです。"],
  ["service", "名", "サービス", "The service was excellent.", "サービスはとてもよかったです。"],
  ["feature", "名", "特徴", "This is the main feature.", "これが主な特徴です。"],
  ["benefit", "名", "利点", "What is the benefit for users?", "利用者の利点は何ですか。"],
  ["survey", "名", "調査", "We ran a short survey.", "短い調査を行いました。"],
  ["customer service", "句", "顧客対応", "Call customer service.", "顧客対応に電話してください。"],
  ["user experience", "句", "使い心地", "Improve the user experience.", "使い心地を改善してください。"],
  ["target customer", "句", "狙う客層", "Who is the target customer?", "狙う客層は誰ですか。"],
  ["press release", "句", "報道発表", "Send the press release today.", "今日報道発表を送ってください。"],
  ["social media", "句", "交流サイト", "Post it on social media.", "交流サイトに投稿してください。"],
  ["word of mouth", "句", "口コミ", "Word of mouth helped sales.", "口コミが売上を助けました。"],
  ["promote a product", "句", "製品を宣伝する", "We will promote the product.", "製品を宣伝します。"],
  ["meet a client", "句", "顧客に会う", "I will meet a client at two.", "2時に顧客に会います。"],
  ["close a sale", "句", "販売をまとめる", "She closed the sale.", "彼女が販売をまとめました。"],
  ["place an order", "句", "発注する", "Please place an order today.", "今日発注してください。"],
  ["make a complaint", "句", "苦情を言う", "The buyer made a complaint.", "買い手が苦情を言いました。"],
  ["handle a claim", "句", "苦情を処理する", "We will handle the claim.", "その苦情を処理します。"],
  ["offer a discount", "句", "割引を出す", "We can offer a discount.", "割引を出せます。"],
  ["sign a contract", "句", "契約する", "They signed the contract.", "彼らは契約しました。"],
  ["keep a promise", "句", "約束を守る", "Always keep a promise.", "いつも約束を守ってください。"],
  ["gain trust", "句", "信頼を得る", "Honest work gains trust.", "誠実な仕事が信頼を得ます。"],
  ["build a relationship", "句", "関係を築く", "We want to build a relationship.", "関係を築きたいです。"],
  ["after-sales", "形", "販売後の", "After-sales support is strong.", "販売後の支援は手厚いです。"],
  ["loyal", "形", "忠実な", "We have loyal customers.", "忠実なお客様がいます。"],
  ["popular", "形", "人気の", "This model is popular.", "この型は人気です。"],
  ["competitive", "形", "競争力のある", "The price is competitive.", "価格に競争力があります。"],
  ["advertise", "動", "宣伝する", "They advertise on the radio.", "ラジオで宣伝しています。"],
  ["recommend", "動", "勧める", "I recommend this plan.", "このプランを勧めます。"],
  ["negotiate", "動", "交渉する", "We will negotiate the price.", "価格を交渉します。"],
  ["deliver", "動", "届ける", "They deliver on Tuesdays.", "火曜に届けます。"],
  ["release", "動", "発売する", "We will release it in July.", "7月に発売します。"],
  ["expand", "動", "広げる", "They want to expand overseas.", "海外へ広げたいと考えています。"],
  ["network", "名", "人脈", "She has a wide network.", "彼女は広い人脈があります。"],
  ["partnership", "名", "提携", "The partnership starts in April.", "提携は4月に始まります。"],
  ["agreement", "名", "合意", "We reached an agreement.", "合意に達しました。"],
  ["condition", "名", "条件", "Check the conditions first.", "まず条件を確認してください。"],
  ["term", "名", "条項", "These terms are fair.", "これらの条項は妥当です。"],
  ["due date", "句", "支払期限", "The due date is Monday.", "支払期限は月曜です。"],
]);

const travel = pack(30001, [
  ["passport", "名", "旅券", "I need my passport.", "旅券が必要です。"],
  ["visa", "名", "査証", "Do I need a visa?", "査証は要りますか。"],
  ["ticket", "名", "切符", "I bought a train ticket.", "列車の切符を買いました。"],
  ["boarding pass", "句", "搭乗券", "Here is my boarding pass.", "これが搭乗券です。"],
  ["gate", "名", "搭乗口", "Which gate is it?", "搭乗口はどこですか。"],
  ["terminal", "名", "ターミナル", "Go to terminal two.", "第2ターミナルへ行ってください。"],
  ["security", "名", "保安検査", "Security is this way.", "保安検査はこちらです。"],
  ["customs", "名", "税関", "I have nothing to declare at customs.", "税関で申告するものはありません。"],
  ["baggage", "名", "荷物", "Where is the baggage claim?", "荷物受け取りはどこですか。"],
  ["suitcase", "名", "スーツケース", "My suitcase is black.", "スーツケースは黒です。"],
  ["delay", "名", "遅れ", "The flight has a delay.", "便に遅れが出ています。"],
  ["cancel", "動", "取り消す", "They canceled the flight.", "その便は取り消されました。"],
  ["depart", "動", "出発する", "The bus departs at eight.", "バスは8時に出発します。"],
  ["arrive", "動", "到着する", "We arrive at noon.", "正午に到着します。"],
  ["transfer", "動", "乗り換える", "I need to transfer in Nagoya.", "名古屋で乗り換える必要があります。"],
  ["check in", "句", "搭乗手続きをする", "Please check in here.", "ここで搭乗手続きをしてください。"],
  ["check out", "句", "出発手続きをする", "I will check out at ten.", "10時に出発手続きをします。"],
  ["take off", "句", "離陸する", "The plane will take off soon.", "まもなく離陸します。"],
  ["land", "動", "着陸する", "We will land in ten minutes.", "10分後に着陸します。"],
  ["aisle", "名", "通路", "I prefer an aisle seat.", "通路側の席がよいです。"],
  ["window", "名", "窓", "A window seat, please.", "窓側の席をお願いします。"],
  ["seat", "名", "席", "Is this seat free?", "この席は空いていますか。"],
  ["platform", "名", "ホーム", "The train is on platform three.", "列車は3番ホームです。"],
  ["fare", "名", "運賃", "How much is the fare?", "運賃はいくらですか。"],
  ["one-way", "形", "片道の", "A one-way ticket, please.", "片道の切符をお願いします。"],
  ["round-trip", "形", "往復の", "I need a round-trip ticket.", "往復の切符が必要です。"],
  ["reserved", "形", "指定の", "This is a reserved seat.", "これは指定席です。"],
  ["nonstop", "形", "直行の", "Is there a nonstop train?", "直行の列車はありますか。"],
  ["late", "形", "遅れている", "The train is late.", "列車が遅れています。"],
  ["early", "形", "早い", "I want an early flight.", "早い便がほしいです。"],
  ["lost", "形", "迷った", "I am lost.", "道に迷いました。"],
  ["excuse me", "句", "すみません", "Excuse me, where is the station?", "すみません、駅はどこですか。"],
  ["how long", "句", "どのくらい", "How long does it take?", "どのくらいかかりますか。"],
  ["how much", "句", "いくら", "How much is this?", "これはいくらですか。"],
  ["where is", "句", "どこにありますか", "Where is the restroom?", "トイレはどこにありますか。"],
  ["this way", "句", "こちらへ", "Please come this way.", "こちらへどうぞ。"],
  ["over there", "句", "あそこ", "The taxi is over there.", "タクシーはあそこです。"],
  ["on the right", "句", "右側に", "The gate is on the right.", "搭乗口は右側です。"],
  ["on the left", "句", "左側に", "The exit is on the left.", "出口は左側です。"],
  ["go straight", "句", "まっすぐ行く", "Go straight and turn left.", "まっすぐ行って左折してください。"],
  ["turn right", "句", "右に曲がる", "Turn right at the light.", "信号で右に曲がってください。"],
  ["turn left", "句", "左に曲がる", "Turn left after the bridge.", "橋のあとで左に曲がってください。"],
  ["next stop", "句", "次の停留所", "Get off at the next stop.", "次の停留所で降りてください。"],
  ["last train", "句", "終電", "What time is the last train?", "終電は何時ですか。"],
  ["bus stop", "句", "バス停", "The bus stop is across the street.", "バス停は通りの向こうです。"],
  ["taxi stand", "句", "タクシー乗り場", "The taxi stand is outside.", "タクシー乗り場は外です。"],
  ["subway", "名", "地下鉄", "Take the subway to city hall.", "市役所までは地下鉄です。"],
  ["airport", "名", "空港", "How do I get to the airport?", "空港へはどう行きますか。"],
  ["station", "名", "駅", "The station is five minutes away.", "駅まで5分です。"],
  ["map", "名", "地図", "Can I see a map?", "地図を見せてもらえますか。"],
  ["hotel", "名", "ホテル", "I booked a hotel near the station.", "駅の近くのホテルを予約しました。"],
  ["reservation", "名", "予約", "I have a reservation.", "予約しています。"],
  ["reception", "名", "受付", "Please go to reception.", "受付へ行ってください。"],
  ["key", "名", "鍵", "Here is your room key.", "部屋の鍵です。"],
  ["room", "名", "部屋", "The room is on the third floor.", "部屋は3階です。"],
  ["single", "形", "1人用の", "A single room, please.", "1人用の部屋をお願いします。"],
  ["double", "形", "2人用の", "Do you have a double room?", "2人用の部屋はありますか。"],
  ["vacancy", "名", "空き", "Do you have a vacancy?", "空きはありますか。"],
  ["breakfast", "名", "朝食", "Is breakfast included?", "朝食は含まれますか。"],
  ["wifi", "名", "無線", "What is the wifi password?", "無線のパスワードは何ですか。"],
  ["towel", "名", "タオル", "Can I have another towel?", "タオルをもう1枚もらえますか。"],
  ["laundry", "名", "洗濯", "Where is the laundry?", "洗濯はどこですか。"],
  ["elevator", "名", "エレベーター", "The elevator is over there.", "エレベーターはあそこです。"],
  ["quiet", "形", "静かな", "I want a quiet room.", "静かな部屋がほしいです。"],
  ["available", "形", "空いている", "Is a room available tonight?", "今夜空いている部屋はありますか。"],
  ["stay", "動", "泊まる", "I will stay for two nights.", "2泊します。"],
  ["book", "動", "予約する", "I booked the room online.", "部屋はネットで予約しました。"],
  ["wake", "動", "起こす", "Please wake me at seven.", "7時に起こしてください。"],
  ["clean", "動", "掃除する", "Please clean the room.", "部屋を掃除してください。"],
  ["check-in time", "句", "到着手続きの時刻", "What is the check-in time?", "到着手続きの時刻は何時ですか。"],
  ["check-out time", "句", "出発の時刻", "Check-out time is eleven.", "出発の時刻は11時です。"],
  ["room service", "句", "部屋への食事", "I called room service.", "部屋への食事を頼みました。"],
  ["front desk", "句", "フロント", "Ask at the front desk.", "フロントで聞いてください。"],
  ["air conditioner", "句", "冷暖房", "The air conditioner is broken.", "冷暖房が壊れています。"],
  ["extra bed", "句", "予備のベッド", "Can I have an extra bed?", "予備のベッドはありますか。"],
  ["non-smoking", "形", "禁煙の", "A non-smoking room, please.", "禁煙の部屋をお願いします。"],
  ["view", "名", "眺め", "The room has a nice view.", "部屋からの眺めがよいです。"],
  ["restaurant", "名", "食事店", "The restaurant is on the first floor.", "食事店は1階です。"],
  ["menu", "名", "献立表", "Can I see the menu?", "献立表を見せてください。"],
  ["order", "名", "注文", "Are you ready to order?", "ご注文はお決まりですか。"],
  ["water", "名", "水", "Can I have some water?", "水をください。"],
  ["coffee", "名", "コーヒー", "One coffee, please.", "コーヒーを1つお願いします。"],
  ["tea", "名", "茶", "I would like tea.", "茶をお願いします。"],
  ["juice", "名", "果汁", "Orange juice, please.", "オレンジの果汁をお願いします。"],
  ["bill", "名", "勘定", "Can I have the bill?", "勘定をお願いします。"],
  ["tip", "名", "心づけ", "Do people leave a tip here?", "ここでは心づけを置きますか。"],
  ["spicy", "形", "辛い", "This dish is too spicy.", "この料理は辛すぎます。"],
  ["sweet", "形", "甘い", "The cake is very sweet.", "ケーキがとても甘いです。"],
  ["hot", "形", "熱い", "The soup is hot.", "スープは熱いです。"],
  ["cold", "形", "冷たい", "I want a cold drink.", "冷たい飲み物がほしいです。"],
  ["delicious", "形", "おいしい", "This is delicious.", "これはおいしいです。"],
  ["vegetarian", "形", "菜食の", "Do you have a vegetarian dish?", "菜食の料理はありますか。"],
  ["allergic", "形", "アレルギーの", "I am allergic to nuts.", "木の実にアレルギーがあります。"],
  ["hungry", "形", "空腹の", "I am hungry.", "空腹です。"],
  ["thirsty", "形", "喉が渇いた", "I am thirsty.", "喉が渇きました。"],
  ["recommend", "動", "勧める", "What do you recommend?", "何をお勧めしますか。"],
  ["taste", "動", "味見する", "Can I taste this?", "味見してもいいですか。"],
  ["share", "動", "分け合う", "Can we share this plate?", "この皿を分け合えますか。"],
  ["for here", "句", "店内で", "For here, please.", "店内でお願いします。"],
  ["to go", "句", "持ち帰りで", "To go, please.", "持ち帰りでお願いします。"],
  ["dine in", "句", "店内で食べる", "We will dine in.", "店内で食べます。"],
  ["table for two", "句", "2人席", "A table for two, please.", "2人席をお願いします。"],
  ["the check", "句", "勘定", "The check, please.", "勘定をお願いします。"],
  ["no ice", "句", "氷なし", "No ice, please.", "氷なしでお願いします。"],
  ["a little", "句", "少し", "Just a little, please.", "少しだけでお願いします。"],
  ["that’s all", "句", "以上です", "That’s all, thank you.", "以上です、ありがとう。"],
  ["it was great", "句", "とてもよかった", "The meal was great.", "食事はとてもよかったです。"],
  ["I am full", "句", "お腹いっぱい", "I am full, thank you.", "お腹いっぱいです、ありがとう。"],
  ["main dish", "句", "主菜", "What is the main dish?", "主菜は何ですか。"],
  ["side dish", "句", "副菜", "I want a small side dish.", "小さな副菜がほしいです。"],
  ["set meal", "句", "定食", "I will have the set meal.", "定食にします。"],
  ["today’s special", "句", "本日のおすすめ", "What is today’s special?", "本日のおすすめは何ですか。"],
  ["shop", "名", "店", "This shop is still open.", "この店はまだ開いています。"],
  ["store", "名", "店舗", "The store closes at eight.", "店舗は8時に閉まります。"],
  ["price", "名", "値段", "The price is on the tag.", "値段は札に書いてあります。"],
  ["size", "名", "大きさ", "Do you have a larger size?", "より大きい大きさはありますか。"],
  ["color", "名", "色", "Do you have this in blue?", "これは青はありますか。"],
  ["cash", "名", "現金", "I will pay in cash.", "現金で払います。"],
  ["card", "名", "カード", "Can I pay by card?", "カードで払えますか。"],
  ["change", "名", "釣り", "Keep the change.", "釣りは結構です。"],
  ["bag", "名", "袋", "A bag, please.", "袋をお願いします。"],
  ["sale", "名", "特売", "Is this on sale?", "これは特売ですか。"],
  ["cheap", "形", "安い", "This is cheaper.", "こっちのほうが安いです。"],
  ["expensive", "形", "高い", "That is too expensive.", "それは高すぎます。"],
  ["free", "形", "無料の", "Is wifi free here?", "ここの無線は無料ですか。"],
  ["open", "形", "開いている", "Are you open now?", "今開いていますか。"],
  ["closed", "形", "閉まっている", "The shop is closed.", "店は閉まっています。"],
  ["try on", "句", "試着する", "Can I try this on?", "試着してもいいですか。"],
  ["too small", "句", "小さすぎる", "This is too small.", "これは小さすぎます。"],
  ["too big", "句", "大きすぎる", "This is too big.", "これは大きすぎます。"],
  ["just looking", "句", "見ているだけ", "I am just looking.", "見ているだけです。"],
  ["I’ll take it", "句", "これにします", "I’ll take it.", "これにします。"],
  ["do you have", "句", "ありますか", "Do you have this in black?", "これは黒はありますか。"],
  ["how much is this", "句", "これはいくらですか", "How much is this shirt?", "このシャツはいくらですか。"],
  ["can I pay", "句", "払えますか", "Can I pay with a card?", "カードで払えますか。"],
  ["receipt please", "句", "領収書を", "A receipt, please.", "領収書をお願いします。"],
  ["souvenir", "名", "みやげ", "I want a small souvenir.", "小さなみやげがほしいです。"],
  ["market", "名", "市場", "The market is busy today.", "今日は市場が混んでいます。"],
  ["pharmacy", "名", "薬局", "Where is the nearest pharmacy?", "一番近い薬局はどこですか。"],
  ["bank", "名", "銀行", "Is there a bank near here?", "この近くに銀行はありますか。"],
  ["museum", "名", "博物館", "The museum opens at ten.", "博物館は10時に開きます。"],
  ["park", "名", "公園", "Let’s walk in the park.", "公園を歩きましょう。"],
  ["hello", "句", "こんにちは", "Hello, my name is Aya.", "こんにちは、アヤです。"],
  ["good morning", "句", "おはよう", "Good morning.", "おはよう。"],
  ["good night", "句", "おやすみ", "Good night.", "おやすみ。"],
  ["thank you", "句", "ありがとう", "Thank you very much.", "どうもありがとう。"],
  ["you’re welcome", "句", "どういたしまして", "You’re welcome.", "どういたしまして。"],
  ["please", "副", "どうか", "Please wait here.", "どうかここで待ってください。"],
  ["sorry", "形", "すまない", "I am sorry I am late.", "遅れてすみません。"],
  ["yes", "副", "はい", "Yes, I understand.", "はい、わかります。"],
  ["no", "副", "いいえ", "No, thank you.", "いいえ、結構です。"],
  ["okay", "形", "承知した", "Okay, I will wait.", "承知しました、待ちます。"],
  ["help", "名", "助け", "I need help.", "助けが必要です。"],
  ["problem", "名", "困りごと", "There is a problem.", "困りごとがあります。"],
  ["emergency", "名", "緊急", "This is an emergency.", "これは緊急です。"],
  ["police", "名", "警察", "Please call the police.", "警察を呼んでください。"],
  ["hospital", "名", "病院", "Where is the hospital?", "病院はどこですか。"],
  ["doctor", "名", "医者", "I need a doctor.", "医者が必要です。"],
  ["pain", "名", "痛み", "I have a pain here.", "ここに痛みがあります。"],
  ["cough", "名", "咳", "I have a cough.", "咳が出ます。"],
  ["fever", "名", "熱", "I have a fever.", "熱があります。"],
  ["medicine", "名", "薬", "I need medicine for a headache.", "頭痛の薬が必要です。"],
  ["lost-and-found", "句", "遺失物係", "Go to lost-and-found.", "遺失物係へ行ってください。"],
  ["I don’t understand", "句", "わかりません", "I don’t understand.", "わかりません。"],
  ["please speak slowly", "句", "ゆっくり話して", "Please speak slowly.", "ゆっくり話してください。"],
  ["do you speak English", "句", "英語は話せますか", "Do you speak English?", "英語は話せますか。"],
  ["can you help me", "句", "助けてもらえますか", "Can you help me?", "助けてもらえますか。"],
  ["I lost my", "句", "〜をなくした", "I lost my wallet.", "財布をなくしました。"],
  ["call a taxi", "句", "タクシーを呼ぶ", "Please call a taxi.", "タクシーを呼んでください。"],
  ["I feel sick", "句", "気分が悪い", "I feel sick.", "気分が悪いです。"],
  ["it hurts", "句", "痛い", "It hurts here.", "ここが痛いです。"],
  ["wait a moment", "句", "少々お待ちを", "Wait a moment, please.", "少々お待ちください。"],
  ["see you", "句", "また会おう", "See you tomorrow.", "また明日。"],
  ["nice to meet you", "句", "はじめまして", "Nice to meet you.", "はじめまして。"],
  ["my name is", "句", "名前は〜です", "My name is Ken.", "ケンです。"],
  ["I am from", "句", "出身は〜", "I am from Japan.", "日本出身です。"],
  ["weather", "名", "天気", "The weather is nice today.", "今日は天気がよいです。"],
  ["rain", "名", "雨", "It may rain later.", "あとで雨が降るかもしれません。"],
  ["sunny", "形", "晴れの", "It is sunny now.", "今は晴れです。"],
  ["cloudy", "形", "曇りの", "It is cloudy this morning.", "今朝は曇りです。"],
  ["warm", "形", "暖かい", "It is warm outside.", "外は暖かいです。"],
  ["chilly", "形", "肌寒い", "It is chilly today.", "今日は肌寒いです。"],
  ["umbrella", "名", "傘", "I need an umbrella.", "傘が必要です。"],
  ["today", "名", "今日", "What are you doing today?", "今日は何をしますか。"],
  ["tomorrow", "名", "明日", "See you tomorrow.", "また明日。"],
  ["yesterday", "名", "昨日", "I arrived yesterday.", "昨日着きました。"],
  ["morning", "名", "朝", "I leave in the morning.", "朝に出発します。"],
  ["evening", "名", "夕方", "Let’s eat in the evening.", "夕方に食べましょう。"],
  ["night", "名", "夜", "The city is quiet at night.", "夜の街は静かです。"],
  ["weekend", "名", "週末", "Are you free this weekend?", "今週末は暇ですか。"],
  ["friend", "名", "友人", "I am meeting a friend.", "友人に会います。"],
  ["family", "名", "家族", "I am traveling with my family.", "家族と旅しています。"],
  ["photo", "名", "写真", "Can you take a photo?", "写真を撮ってもらえますか。"],
  ["phone", "名", "電話", "My phone is out of battery.", "電話の電池が切れました。"],
  ["charger", "名", "充電器", "I need a charger.", "充電器が必要です。"],
  ["cashless", "形", "現金を使わない", "This shop is cashless.", "この店は現金を使いません。"],
  ["local", "形", "地元の", "I want local food.", "地元の食べ物がほしいです。"],
  ["famous", "形", "有名な", "This temple is famous.", "この寺は有名です。"],
  ["crowded", "形", "混んだ", "The train is crowded.", "列車が混んでいます。"],
  ["safe", "形", "安全な", "Is this area safe at night?", "この辺りは夜でも安全ですか。"],
  ["near", "形", "近い", "Is the station near here?", "駅はこの近くですか。"],
  ["far", "形", "遠い", "The hotel is not far.", "ホテルは遠くありません。"],
  ["enjoy", "動", "楽しむ", "Enjoy your stay.", "滞在を楽しんでください。"],
  ["visit", "動", "訪れる", "I want to visit the castle.", "城を訪れたいです。"],
  ["walk", "動", "歩く", "We can walk from here.", "ここから歩けます。"],
  ["rest", "動", "休む", "I need to rest.", "休む必要があります。"],
  ["wait", "動", "待つ", "Please wait here.", "ここで待ってください。"],
  ["look", "動", "見る", "Look at that building.", "あの建物を見てください。"],
  ["have a nice day", "句", "よい一日を", "Have a nice day.", "よい一日を。"],
  ["take care", "句", "気をつけて", "Take care.", "気をつけて。"],
  ["have fun", "句", "楽しんで", "Have fun in Kyoto.", "京都を楽しんで。"],
  ["see the sights", "句", "見物する", "We will see the sights tomorrow.", "明日見物します。"],
  ["take a break", "句", "一休みする", "Let’s take a break.", "一休みしましょう。"],
  ["get some rest", "句", "休む", "You should get some rest.", "休んだほうがいいです。"],
  ["out of battery", "句", "電池切れ", "My phone is out of battery.", "電話が電池切れです。"],
  ["can I take a photo", "句", "写真を撮っていいですか", "Can I take a photo here?", "ここで写真を撮っていいですか。"],
  ["what time is it", "句", "何時ですか", "What time is it now?", "今何時ですか。"],
  ["see you later", "句", "また後で", "See you later.", "また後で。"],
]);

function unique(words, name) {
  const ids = new Set();
  const heads = new Set();
  for (const word of words) {
    if (ids.has(word.id)) throw new Error(`${name} duplicate id ${word.id}`);
    if (heads.has(word.word.toLowerCase())) throw new Error(`${name} duplicate ${word.word}`);
    ids.add(word.id);
    heads.add(word.word.toLowerCase());
  }
}

unique(business, "business");
unique(travel, "travel");
writeFileSync("src/data/business.json", JSON.stringify(business, null, 2) + "\n");
writeFileSync("src/data/travel.json", JSON.stringify(travel, null, 2) + "\n");
console.log(`business ${business.length} travel ${travel.length}`);
